### ISSUE TITLE
Custom Filename structure

### ISSUE THREAD

**Issue by JustinByrne** [hama3254/Crunchyroll-Downloader-v3.0#133] opened 2021-01-10 12:55 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem per se, however, having the ability for videos to be named with a custom naming structure will prevent me from having to rename all videos to match Plex naming format.

**Describe the solution you'd like**
In the Settings->Output menu there is currently a filename drop-down. If an option of `custom` could be added here that shows an input field that can use predefined options to name the files as needed, e.g.

```
[series name] - s[season number XX]e[episode number XX] - [episode name]
```

This could then output something like this as the filename

```
My Hero Academia - s01e02 - What it takes to be a hero.mp4
```

This could allow for a multitude of different naming options, allow naming structures for multiple streaming platforms.

**Describe alternatives you've considered**
At the moment I have a PowerShell script that I use to rename the files on mass, however, it would be less time if done at the beginning.

**Additional context**
No additional context

**Comment by hama3254** [comment] 2021-01-10 16:49
> **Describe the solution you'd like**
> In the Settings->Output menu there is currently a filename drop-down. If an option of `custom` could be added here that shows an input field that can use predefined options to name the files as needed, e.g.
> 
> ```
> [series name] - s[season number XX]e[episode number XX] - [episode name]
> ```
> 
> This could then output something like this as the filename
> 
> ```
> My Hero Academia - s01e02 - What it takes to be a hero.mp4
> ```

That is with the current naming method not possible, i just use the text from the crunchyroll website as name which means it is different for each  language : 
![grafik](https://user-images.githubusercontent.com/52826614/104128632-142b8500-5369-11eb-89d1-9fabf1904be5.png)

I would need to rewrite the entire naming to get the episode and season number without the language specific words and for that will not happen until we know more about the Funimation/Sony bought Cruchyroll thing and what changes with it.

**Comment by hama3254** [comment] 2021-02-07 12:33
due to issues found with movies on crunchyroll #166 i reworked the naming once again and added the requested feature. 
you can now set prefixes for Season and Episodes as you like.
Movies ignore the episode/season numbers because they don't have any.
Season numbers also get ignored on Crunchyroll if it is marked as season "0".
![grafik](https://user-images.githubusercontent.com/52826614/107146126-76ff4480-6946-11eb-859a-0befc5d193b1.png)

i also added the option to switch episode name and number 
![grafik](https://user-images.githubusercontent.com/52826614/107146482-f2fa8c00-6948-11eb-8bcc-ffa83cde9710.png)

**Comment by JustinByrne** [comment] 2021-02-07 12:50
Thanks, I'll download the latest release and close once tested.

**Comment by hama3254** [comment] 2021-02-12 12:50
i don't see any complaints so i assume it works as intended and close this.

**Closed by hama3254** 2021-02-12 12:50 UTC
Labels: On Hold

**Comment by JustinByrne** [comment] 2021-02-12 12:51
> i don't see any complaints so i assume it works as intended and close this. 

Sorry meant to close this
