### ISSUE TITLE
Funi: Fail to add from a season page - 0 episodes added to Download queue 

### ISSUE THREAD

**Issue by theruleof4** [hama3254/Crunchyroll-Downloader-v3.0#297] opened 2021-06-20 17:49 UTC
For Funimation series, I cannot add any episodes from a season to the download queue via the web browser. I have a premium acc and is not working, a few weeks ago I've tried and worked well, but not now. 
If I add a single episode, playing or via a link, works, but not the entire season.

I'm on 3.7.8.6 version 

![image](https://user-images.githubusercontent.com/62116034/122683436-884e3c80-d1d5-11eb-9702-e394c3853981.png)

**Comment by hama3254** [comment] 2021-06-20 18:28
funimation changed there website and that feature does not work with the new one but i already added the same style of mass download like on CR but that is only in the new `Crunchyroll-Downloader-v3.8-Beta-U8`


>with the new API i finally added the same style of mass download as on Crunchyroll and Anime On Demand. 
Now i just need completely rewrite the download for Funimation for the new JavaScript based site.
>
>https://user-images.githubusercontent.com/52826614/118817256-5171c780-b8b3-11eb-8305-698cc03a9e6e.mp4

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/271#issuecomment-844088997_

**Comment by theruleof4** [comment] 2021-06-20 19:15
Oh, I see. I downloaded the U8 version of the beta, paste the link and some errors happened:

![image](https://user-images.githubusercontent.com/62116034/122685539-57283900-d1e2-11eb-816e-55659ed61545.png)
![image](https://user-images.githubusercontent.com/62116034/122685542-61e2ce00-d1e2-11eb-80a2-388b5b33153c.png)
![image](https://user-images.githubusercontent.com/62116034/122685565-86d74100-d1e2-11eb-92bb-daa56af69354.png)
![image](https://user-images.githubusercontent.com/62116034/122685580-a1a9b580-d1e2-11eb-8212-0a27193ac742.png)

After these errors, I can not select any season or episodes.

**Comment by hama3254** [comment] 2021-06-20 20:01
That looks like some problems with the data processing, i test that tomorrow and see what's wrong. 

In the mean time i can only suggest you either do the episodes one by one or try the add-on, v0.6 has just been released with support for the new funimation UI [You can find all information you need here](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/296)

**Comment by theruleof4** [comment] 2021-06-20 21:28
> That looks like some problems with the data processing, i test that tomorrow and see what's wrong.
> 
> In the mean time i can only suggest you either do the episodes one by one or try the add-on, v0.6 has just been released with support for the new funimation UI [You can find all information you need here](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/296)

Yeah, I check this add-on for chrome, but for some reason, It not works with either, after clicking the button to "add this episode" the program freezes and not works. :(

**Comment by firecrauter** [comment] 2021-06-21 02:42
Does this happen to someone else on Crunchyroll?

If I put Spanish subtitles (LA)
and this link: www.crunchyroll.com/es/my-hero-academia
no episode appears.

But with this:
www.crunchyroll.com/my-hero-academia
They appear, but after messages that only subs are in en-us

**Comment by hama3254** [comment] 2021-06-21 04:29
> Yeah, I check this add-on for chrome, but for some reason, It not works with either, after clicking the button to "add this episode" the program freezes and not works. 

Where do you try the add-on, on a single video or on a anime overview Page?
On the page with all episodes that button should not even be visible, there should be a selection button which loads a JavaScript that gives you a screen like in #296.

**Comment by hama3254** [comment] 2021-06-21 04:56
> Does this happen to someone else on Crunchyroll?
> 
> If I put Spanish subtitles (LA)
> and this link: [www.crunchyroll.com/es/my-hero-academia](http://www.crunchyroll.com/es/my-hero-academia)
> no episode appears.
> 
> But with this:
> [www.crunchyroll.com/my-hero-academia](http://www.crunchyroll.com/my-hero-academia)
> They appear, but after messages that only subs are in en-us

That seems to me like a normal Crunchyroll behavior, if the selected language is not available for that anime it won't show the episode on the website.
Please check if the episode are available with Spanish subs in your Chrome/Firefox/Edge.

**Comment by firecrauter** [comment] 2021-06-21 05:34
> > Does this happen to someone else on Crunchyroll?
> > If I put Spanish subtitles (LA)
> > and this link: [www.crunchyroll.com/es/my-hero-academia](http://www.crunchyroll.com/es/my-hero-academia)
> > no episode appears.
> > But with this:
> > [www.crunchyroll.com/my-hero-academia](http://www.crunchyroll.com/my-hero-academia)
> > They appear, but after messages that only subs are in en-us
> 
> That seems to me like a normal Crunchyroll behavior, if the selected language is not available for that anime it won't show the episode on the website.
> Please check if the episode are available with Spanish subs in your Chrome/Firefox/Edge.
All the episodes of the 4th and 5th season have subtitles Es-la and Es-es.
But no episode appears.

Something must be different on that page of my hero academia so as not to extract subs from other languages, only English
![image](https://user-images.githubusercontent.com/7044466/122711551-b6189d00-d238-11eb-8725-a9fac81567fd.png)

**Comment by firecrauter** [comment] 2021-06-21 05:37
> > Does this happen to someone else on Crunchyroll?
> > If I put Spanish subtitles (LA)
> > and this link: [www.crunchyroll.com/es/my-hero-academia](http://www.crunchyroll.com/es/my-hero-academia)
> > no episode appears.
> > But with this:
> > [www.crunchyroll.com/my-hero-academia](http://www.crunchyroll.com/my-hero-academia)
> > They appear, but after messages that only subs are in en-us
> 
> That seems to me like a normal Crunchyroll behavior, if the selected language is not available for that anime it won't show the episode on the website.
> Please check if the episode are available with Spanish subs in your Chrome/Firefox/Edge.

You were right, the problem is that I use a vpn from another country, and there is no boku no hero with other languages, only English

**Comment by hama3254** [comment] 2021-06-21 15:21
please try [`Crunchyroll-Downloader-v3.8-Beta-U9`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta) it should fix this issue.

**Comment by theruleof4** [comment] 2021-06-21 16:04
> > Yeah, I check this add-on for chrome, but for some reason, It not works with either, after clicking the button to "add this episode" the program freezes and not works.
> 
> Where do you try the add-on, on a single video or on a anime overview Page?
> On the page with all episodes that button should not even be visible, there should be a selection button which loads a JavaScript that gives you a screen like in #296.

Sorry for the late reply. I've tested on the anime page and show me this:

![image](https://user-images.githubusercontent.com/62116034/122792908-f99ef580-d290-11eb-8b7d-fb98c4257730.png)

When I play an episode, the add on works

**Comment by theruleof4** [comment] 2021-06-21 16:04
> > Oh, I see. I downloaded the U8 version of the beta, paste the link and some errors happened:
> 
> please try [`Crunchyroll-Downloader-v3.8-Beta-U9`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta) it should fix this issue.

I'll try now

**Comment by theruleof4** [comment] 2021-06-21 16:14
> > Oh, I see. I downloaded the U8 version of the beta, paste the link and some errors happened:
> 
> please try [`Crunchyroll-Downloader-v3.8-Beta-U9`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta) it should fix this issue.

This time, shown me the message "No video found" after I posted this link https://www.funimation.com/shows/moriarty-the-patriot/, and then the screen to choose the episodes appeared but show no option to select, and the error message again:

![image](https://user-images.githubusercontent.com/62116034/122794385-944c0400-d292-11eb-80d5-448ee1182389.png)

**Comment by hama3254** [comment] 2021-06-21 17:04
> 
> Sorry for the late reply. I've tested on the anime page and show me this:
> 
> ![image](https://user-images.githubusercontent.com/62116034/122792908-f99ef580-d290-11eb-8b7d-fb98c4257730.png)
> 
> When I play an episode, the add on works

i see it fails to detect the episodes in that case, just why would be interesting to know since it works for me with the add-on v0.6 on the same anime for both Firefox and Chrome and i even use a Brazil VPN to get the same version of the webpage.
![grafik](https://user-images.githubusercontent.com/52826614/122800437-3683e000-d2c3-11eb-98ab-9e9b69bb0bd1.png)

**Comment by hama3254** [comment] 2021-06-21 17:17
> This time, shown me the message "No video found" after I pasted this link https://www.funimation.com/shows/moriarty-the-patriot/, and then the screen to choose the episodes appeared but show no option to select, and the error message again:

Could you add the complete text from the error here? it is hard to fix issues that don't happen to myself 

https://user-images.githubusercontent.com/52826614/122801997-23720f80-d2c5-11eb-93ae-f26cfc5309b8.mp4

**Comment by theruleof4** [comment] 2021-06-21 18:24
> > This time, shown me the message "No video found" after I pasted this link https://www.funimation.com/shows/moriarty-the-patriot/, and then the screen to choose the episodes appeared but show no option to select, and the error message again:
> 
> Could you add the complete text from the error here? it is hard to fix issues that don't happen to myself
> 
>  video.mp4

I believe the error was caused because the add on, now I tried with beta 9 without the add on and has a different issue:


https://user-images.githubusercontent.com/62116034/122809254-3de7c100-d2a4-11eb-9901-14d7dfd2e722.mp4

**Comment by theruleof4** [comment] 2021-06-21 18:27
On another try, I got this message:
![image](https://user-images.githubusercontent.com/62116034/122809912-180eec00-d2a5-11eb-97e7-81e8c0f039b8.png)

**Comment by hama3254** [comment] 2021-06-21 19:29
> 
> 
> On another try, I got this message:
> ![image](https://user-images.githubusercontent.com/62116034/122809912-180eec00-d2a5-11eb-97e7-81e8c0f039b8.png)

That perfectly sums up the issue, you need to be logged in at the build-in webbrowser so the downloader get access to the cookies which are required for premium episodes.



> I believe the error was caused because the add on, now I tried with beta 9 without the add on and has a different issue:
>![grafik](https://user-images.githubusercontent.com/52826614/122816812-7bb20d00-d2d7-11eb-9fd8-359421afb38a.png)

This is a random issue if the downloader is unable to get the data from there API then it detects it and gives that error message.

**Comment by theruleof4** [comment] 2021-06-21 20:57
> That perfectly sums up the issue, you need to be logged in at the build-in webbrowser so the downloader get access to the cookies which are required for premium episodes.
> 
I'm already logged. Do I need to keep the build-in webbrowser opened while it loads the episodes?

**Comment by hama3254** [comment] 2021-06-22 04:56
> I'm already logged. Do I need to keep the build-in webbrowser opened while it loads the episodes?

No it loads fine in the background.

**Comment by theruleof4** [comment] 2021-06-22 21:37
> > I'm already logged. Do I need to keep the build-in webbrowser opened while it loads the episodes?
> 
> No it loads fine in the background.

I don't know what I am doing wrong, I keep getting the _v1json data_ error

**Comment by hama3254** [comment] 2021-06-23 04:13
You should find the exact error Message in the console which can be displayed clicking the gray bar on the very bottom of the downloader

> ![grafik](https://user-images.githubusercontent.com/52826614/119235080-01a03400-bb31-11eb-9e79-5c79049482bb.png)

**Comment by theruleof4** [comment] 2021-06-24 19:46
> You should find the exact error Message in the console which can be displayed clicking the gray bar on the very bottom of the downloader
> 
> > ![grafik](https://user-images.githubusercontent.com/52826614/119235080-01a03400-bb31-11eb-9e79-5c79049482bb.png)

This is what shows:

```
Web server started at: 127.0.0.1:8080
24/06/2021 16:42:06.71
error- getting SeasonJson data
https://title-api.prd.funimationsvc.com/v1/seasons/1174925?region=BR&deviceType=web&locale=pt
24/06/2021 16:43:43.263
error- getting v1Json data
System.Net.WebException: O servidor remoto retornou um erro: (404) Não Localizado.
   em System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   em System.Net.WebClient.DownloadString(Uri address)
   em System.Net.WebClient.DownloadString(String address)
   em Crunchyroll_Downloader.Main.GetFunimationJS_Video(String v1JsonURL) na D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0\Crunchyroll Downloader\Main.vb:linha 3622

```

**Comment by hama3254** [comment] 2021-06-25 19:59
i can't tell where the 404 comes from but update 10 of the 3.8-Beta has some big improvements for getting the Json from funimation and if it still not works it added more information into the console in that part oft the error message. 

https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta

**Comment by NatsuFT36** [comment] 2021-06-26 05:30
Hello, the button used by the GeckoFX browser for Funimation does not access or it does not have the website and that is why I have to write the site

**Comment by hama3254** [comment] 2021-06-26 08:16
> Hello, the button used by the GeckoFX browser for Funimation does not access or it does not have the website and that is why I have to write the site

The Funimation button was never made to navigate to funimation, this issue has even been made because it does not work anymore as intended due to changes on the website.
The button will be removed in some future update.

**Comment by theruleof4** [comment] 2021-06-26 22:56
> i can't tell where the 404 comes from but update 10 of the 3.8-Beta has some big improvements for getting the Json from funimation and if it still not works it added more information into the console in that part oft the error message.
> 
> https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta

I'll try later this U10

**Comment by hama3254** [comment] 2021-07-03 10:22
If there is no feedback then i can close this here.
You can open a new issue at any time.

**Closed by hama3254** 2021-07-03 10:22 UTC
