### ISSUE TITLE
Can't download anything

### ISSUE THREAD

**Issue by gastonx9** [hama3254/Crunchyroll-Downloader-v3.0#929] opened 2024-04-07 19:07 UTC
I'm having this issue since 6 months ago approx.
tried with different versions but still the same
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166330306/335a35f4-e5a8-4fad-ac6c-84ce35f10fd6)
What can I do?

**Comment by oQnz** [comment] 2024-04-08 00:14
Same issue can't download anything at all

![2024-04-08 03_13_33-Crunchyroll Downloader](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166345120/4af3eb65-5b5d-4838-88d8-143375e27249)

**Comment by gamer191** [comment] 2024-04-08 01:48
The solution would be to download cacert.pem from https://curl.se/docs/caextract.html. I don’t know where to save it to though

**Comment by hama3254** [comment] 2024-04-08 04:38
@gastonx9 issues #836 and #859 had the same problem caused by the Anti-Virus software.
Disabling it might help to get it working.

@oQnz not quite the same error but #795 also seems to indicate that the Anti-Virus software is to blame here.

**Comment by hama3254** [comment] 2024-04-08 04:45
> The solution would be to download cacert.pem from https://curl.se/docs/caextract.html. I don’t know where to save it to though

This files is actually included with the downloader and has somewhat recently been updated.

If someone wants (or needs) to update the file, a tldr from a former issue:

>You can try to get the [`cacert.pem`](https://curl.se/ca/cacert.pem) from curl and replace the existing `curl-ca-bundle.crt` with it.
[You can see the exact path in the error message.](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/906#issuecomment-1975087206)

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/906#issuecomment-1975115063_

**Comment by gamer191** [comment] 2024-04-08 07:16
@oQnz is it possible that crunchyroll is blocked by your wifi network? Next time that happens, try visiting crunchyroll in your browser

**Comment by gastonx9** [comment] 2024-04-11 20:02
Thanks, it worked the antivirus software stuff, but now i'm having another problem:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166330306/f3286b0e-0158-4cfd-995a-f865fddbe787)
and this is what the log says:

11/4/2024 16:59:47 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" -headers "ACCEPT-ENCODING: *" -protocol_whitelist file,http,https,tcp,tls,crypto,data -allowed_extensions ALL -i "E:\Crunchyroll-Downloader-v3.20\CRD-Temp-File-ng9vfmjehn6nd0t0.m3u8" -metadata:s:a:0 language=jpn -c copy -c:a copy -bsf:a aac_adtstoasc "E:\Torrent downloads\para seedear\Laid-Back Camp Season 1 Episode 1.mp4"

11/4/2024 16:59:47 ffmpeg version 5.1-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
11/4/2024 16:59:47   built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
11/4/2024 16:59:47   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
11/4/2024 16:59:47   libavutil      57. 28.100 / 57. 28.100
11/4/2024 16:59:47   libavcodec     59. 37.100 / 59. 37.100
11/4/2024 16:59:47   libavformat    59. 27.100 / 59. 27.100
11/4/2024 16:59:47   libavdevice    59.  7.100 / 59.  7.100
11/4/2024 16:59:47   libavfilter     8. 44.100 /  8. 44.100
11/4/2024 16:59:47   libswscale      6.  7.100 /  6.  7.100
11/4/2024 16:59:47   libswresample   4.  7.100 /  4.  7.100
11/4/2024 16:59:47   libpostproc    56.  6.100 / 56.  6.100
11/4/2024 16:59:47 [hls @ 0000020085993e80] Skip ('#EXT-X-VERSION:5')
11/4/2024 16:59:47 [hls @ 0000020085993e80] Opening 'https://fy.v.vrv.co/evs3/c6aee07d5f834c9da64dacf925742861/assets/4246647c99e9fa1463dae0b4f6e353fc_3429659.mp4/encryption.key?t=exp=1712887217~acl=/evs3/c6aee07d5f834c9da64dacf925742861/assets/4246647c99e9fa1463dae0b4f6e353fc_3429659.mp4/*~hmac=620f29a63188fb3967d7f0f72f1b7ea0e8368e5baea08f245c1fae22faf96001' for reading
11/4/2024 16:59:48 [hls @ 0000020085993e80] Opening 'crypto+https://fy.v.vrv.co/evs3/c6aee07d5f834c9da64dacf925742861/assets/4246647c99e9fa1463dae0b4f6e353fc_3429659.mp4/seg-1-v1-a1.ts?t=exp=1712887217~acl=/evs3/c6aee07d5f834c9da64dacf925742861/assets/4246647c99e9fa1463dae0b4f6e353fc_3429659.mp4/*~hmac=620f29a63188fb3967d7f0f72f1b7ea0e8368e5baea08f245c1fae22faf96001' for reading
11/4/2024 16:59:49 Option user_agent not found.

11/4/2024 16:59:49 

> @gastonx9 issues #836 and #859 had the same problem caused by the Anti-Virus software. Disabling it might help to get it working.
> 
> @oQnz not quite the same error but #795 also seems to indicate that the Anti-Virus software is to blame here.

**Comment by hama3254** [comment] 2024-04-12 17:38
> Thanks, it worked disabling the anti-virus software. and sorry for asking a repeated issue.

Good to know that it is the same issue and don't worry that it was an repeated issue, i am always glad i can help.

I think i can close this issue now.

**Closed by hama3254** 2024-04-12 17:38 UTC
