### ISSUE TITLE
Leftovers in CRD-Temp-File-xxxxxxxxxxxxxxxx

### ISSUE THREAD

**Issue by ralvarador** [hama3254/Crunchyroll-Downloader-v3.0#99] opened 2020-12-04 14:21 UTC
Well... it is not like an issue but a behavior not present in previous release.
Using the v3.6.2, downloading CR titles, once finished the downloading, still left some leftovers stored in folders with pattern CRD-Temp-File-xxxxxxxxxxxxxxxx, a bunch of files with extensions .ts.
Options active:
Simultaneous download: 1
Create Log: Active
Redirect to the queue: Active
Hybrid download: Active

**Comment by hama3254** [comment] 2020-12-04 19:00
that is the cached video stream, i disabled the delete method for debagging during development and it seems like i did not turn it on again.
The downloader still should delete the files in the main download directory and in it's program folder after you close it, the only remains that can be there after that should be in subfolders, you can delete them without any trouble after the download is finished.
The next version should work again as intended, i'm sorry for that.

**Closed** 2020-12-04 19:10 UTC
