### ISSUE TITLE
App crashes after downloading a couple of episodes for some animes

### ISSUE THREAD

**Issue by liloss17** [hama3254/Crunchyroll-Downloader-v3.0#79] opened 2020-10-27 22:03 UTC
sometimes after an episode or two are finished and sometimes when the whole anime is finished.

bonus question, how to download animes that aren't available in my region now that there's no "US cookie" in the settings, i tried vpn but i cant keep it on at all time since i only have 15gb limit and its really slow so i wait for an episode to start then i turn off the vpn, sometimes it works but mostly it doesn't

**Comment by x3inspire** [comment] 2020-10-27 23:17
Happened to me too, suddenly the apps closed without showing any error.

**Comment by hama3254** [comment] 2020-10-28 05:57
> sometimes after an episode or two are finished and sometimes when the whole anime is finished.

Any more information?
Like did you use the hybride Mode ?

@x3inspire 

> Happened to me too, suddenly the apps closed without showing any error.

That's a window 10 "feature" ...
I noticed with the Gecko/Firefox problems that windows does not displaying anything and just writes it into the event view log.
If that happens again please take a look there.



> there's no "US cookie" in the settings

The US cookie works only for crunchyroll that why it has been moved into the crunchyroll settings.


> tried vpn but i cant keep it on at all time since i only have 15gb limit

Technically it should be enough if you enabled the VPN then open the downloader and login if you have an account then you actually can disable the VPN again since CR saves the value in a cookie and ignores the IP if you have a valid session (that's also how the us unlock works)

**Comment by x3inspire** [comment] 2020-10-30 10:59
`Error	30/10/2020 18:50:44	.NET Runtime	1026	None`
`Log Name:      Application
Source:        .NET Runtime
Date:          30/10/2020 18:50:44
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ROG
Description:
Application: Crunchyroll Downloader.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.Directory.DeleteHelper(System.String, System.String, Boolean, Boolean, WIN32_FIND_DATA ByRef)
   at System.IO.Directory.Delete(System.String, System.String, Boolean, Boolean)
   at System.IO.Directory.Delete(System.String, Boolean)
   at Crunchyroll_Downloader.CRD_List_Item.TestOutput(System.Object, System.Diagnostics.DataReceivedEventArgs)
   at System.Diagnostics.Process.ErrorReadNotifyUser(System.String)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(System.IAsyncResult)
   at System.IO.Stream+ReadWriteTask.InvokeAsyncCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.IO.Stream+ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-30T10:50:44.4639277Z" />
    <EventRecordID>19616</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>ROG</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Crunchyroll Downloader.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.Directory.DeleteHelper(System.String, System.String, Boolean, Boolean, WIN32_FIND_DATA ByRef)
   at System.IO.Directory.Delete(System.String, System.String, Boolean, Boolean)
   at System.IO.Directory.Delete(System.String, Boolean)
   at Crunchyroll_Downloader.CRD_List_Item.TestOutput(System.Object, System.Diagnostics.DataReceivedEventArgs)
   at System.Diagnostics.Process.ErrorReadNotifyUser(System.String)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(System.IAsyncResult)
   at System.IO.Stream+ReadWriteTask.InvokeAsyncCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.IO.Stream+ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

</Data>
  </EventData>
</Event>`


`Error	30/10/2020 18:50:44	Application Error	1000	(100)`
`Log Name:      Application
Source:        Application Error
Date:          30/10/2020 18:50:44
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ROG
Description:
Faulting application name: Crunchyroll Downloader.exe, version: 3.5.6.0, time stamp: 0x5f909f1a
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x979ddb1d
Exception code: 0xe0434352
Fault offset: 0x00129ab2
Faulting process id: 0x2258
Faulting application start time: 0x01d6ae61cb08f9ac
Faulting application path: F:\Crunchyroll Downloader\Crunchyroll Downloader.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 30c44d5c-d79c-4ce5-8e7e-c2197f137313
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-30T10:50:44.6459591Z" />
    <EventRecordID>19617</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>ROG</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Crunchyroll Downloader.exe</Data>
    <Data>3.5.6.0</Data>
    <Data>5f909f1a</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.572</Data>
    <Data>979ddb1d</Data>
    <Data>e0434352</Data>
    <Data>00129ab2</Data>
    <Data>2258</Data>
    <Data>01d6ae61cb08f9ac</Data>
    <Data>F:\Crunchyroll Downloader\Crunchyroll Downloader.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>30c44d5c-d79c-4ce5-8e7e-c2197f137313</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>`

**Comment by hama3254** [comment] 2020-10-30 12:49
> 
> 
> The error log is too long, you can check it here?
> 
> https://pastebin.com/AR8CDugg
> 
> https://pastebin.com/dK2FVL9H

Yes perfect, that is what i need!

The problem is `at System.IO.Directory.DeleteHelper` on the output ` Crunchyroll_Downloader.CRD_List_Item.TestOutput`

even tho i don't know what `at System.IO.__Error.WinIOError(Int32, System.String)` means but i can at least stop the app from crashing

**Comment by liloss17** [comment] 2020-10-31 12:52
so the fix in next update?

**Comment by hama3254** [comment] 2020-10-31 22:59
> so the fix in next update?

it should be fixed, the problem with such random error is that is hard to check if there are there.
you can try v3.5.7 and give me feedback if you want.

**Comment by x3inspire** [comment] 2020-11-09 05:53
`Faulting application name: Crunchyroll Downloader.exe, version: 3.5.7.0, time stamp: 0x5f9de5a7
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x979ddb1d
Exception code: 0xe0434352
Fault offset: 0x00129ab2
Faulting process id: 0x11d4
Faulting application start time: 0x01d6b65c05c9af09
Faulting application path: C:\Users\X3\Downloads\Crunchyroll-Downloader.v3.5.7\Crunchyroll Downloader.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: c8dfa96a-322b-4b98-973f-a726c39c1621
Faulting package full name: 
Faulting package-relative application ID: `

Still crash with new version.

**Comment by hama3254** [comment] 2020-11-11 11:47
> Still crash with new version.

i need the .NET log that does not help me.

**Comment by x3inspire** [comment] 2020-11-11 13:47
> Log Name:      Application
Source:        .NET Runtime
Date:          11/8/2020 9:50:50 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-IP7Q3IN
Description:
Application: Crunchyroll Downloader.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.WebClient.DownloadFile(System.Uri, System.String)
   at System.Net.WebClient.DownloadFile(System.String, System.String)
   at Crunchyroll_Downloader.CRD_List_Item.DownloadHybrid(System.String, System.String, System.String)
   at Crunchyroll_Downloader.CRD_List_Item+_Closure$__116-0._Lambda$__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-09T05:50:50.5540981Z" />
    <EventRecordID>219</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-IP7Q3IN</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Crunchyroll Downloader.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.WebClient.DownloadFile(System.Uri, System.String)
   at System.Net.WebClient.DownloadFile(System.String, System.String)
   at Crunchyroll_Downloader.CRD_List_Item.DownloadHybrid(System.String, System.String, System.String)
   at Crunchyroll_Downloader.CRD_List_Item+_Closure$__116-0._Lambda$__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

</Data>
  </EventData>
</Event>

**Comment by hama3254** [comment] 2020-11-13 15:08
@x3inspire please try the v3.6 pre-relase and give me feedback about that.

**Comment by x3inspire** [comment] 2020-11-13 18:08
> @x3inspire please try the v3.6 pre-relase and give me feedback about that.

Still crashed.

`Application: Crunchyroll Downloader.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.StreamWriter.CreateFile(System.String, Boolean, Boolean)
   at System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding, Int32, Boolean)
   at System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding)
   at Crunchyroll_Downloader.CRD_List_Item.DownloadHybrid(System.String, System.String, System.String)
   at Crunchyroll_Downloader.CRD_List_Item+_Closure$__118-0._Lambda$__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by hama3254** [comment] 2020-11-13 20:10
for that i have no idea how you even manage to get there.
i create a temp folder for the download on the beginning and if it fails to create it should exit with an error.
even if the main path does not exist it should create the whole structure or fail and exit 
![grafik](https://user-images.githubusercontent.com/52826614/99116113-c2c67a00-25f3-11eb-8470-c2f682e57bef.png)

**Comment by x3inspire** [comment] 2020-11-14 01:09
So what should i do from my side?

**Comment by hama3254** [comment] 2020-11-14 11:05
> So what should i do from my side?

First of all i would need to know about what OS you are using, because my Windows 10 1909 simply does not crash the app on such errors it displays a error message on default . 
![grafik](https://user-images.githubusercontent.com/52826614/99145657-ed0a4d00-2670-11eb-9a9d-d6a0ab451d41.png)

then a info about how often that happens would be nice.

and it seems to me that your problem is mainly the hybrid mode, i would try to deactivate it and see it that get more stable.

**Comment by x3inspire** [comment] 2020-11-19 16:39
> Application: Crunchyroll Downloader.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.WebClient.DownloadDataInternal(System.Uri, System.Net.WebRequest ByRef)
   at System.Net.WebClient.DownloadString(System.Uri)
   at System.Net.WebClient.DownloadString(System.String)
   at Crunchyroll_Downloader.CRD_List_Item.DownloadHybrid(System.String, System.String, System.String)
   at Crunchyroll_Downloader.CRD_List_Item+_Closure$__118-0._Lambda$__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by x3inspire** [comment] 2020-11-19 17:17
Ok seem like having problem with this anime
[https://www.crunchyroll.com/photon-the-idiot-adventures](url)

**Comment by hama3254** [comment] 2020-11-19 21:31
i'm still unable to find any problem. 
![grafik](https://user-images.githubusercontent.com/52826614/99726372-b724f880-2ab6-11eb-8114-c011f3819b9c.png)


did you try that ? 

> and it seems to me that your problem is mainly the hybrid mode, i would try to deactivate it and see it that get more stable.

**Closed** 2020-11-23 20:03 UTC
