### ISSUE TITLE
[Request] Add support for musicvideos/concerts

### ISSUE THREAD

**Issue by Akamaru** [hama3254/Crunchyroll-Downloader-v3.0#704] opened 2023-03-04 12:07 UTC
Crunchyroll added music videos and concerts to their site today. 
https://www.crunchyroll.com/music 
It would be nice if the downloader could download these.

**Comment by hama3254** [comment] 2023-03-05 12:06
i made a release of the latest git version as [v3.14.5](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.14.5) since i am not really into musicvideos/concerts i don't test that much for this so feedback is required to solve any upcomming issues.

**Comment by Akamaru** [comment] 2023-03-05 12:51
Thank you! Music videos seems to work, I had no problem here.
But I can't download any concert. I get this error:
![error](https://img.ponywave.de/images/2023/03/05/Crunchyroll_Downloader_2023-03-05_13-46-23.png)

Do you need more info?

**Comment by hama3254** [comment] 2023-03-05 13:35
>Do you need more info?

If i had looked at one concert url then the issue was not to be overlooked but i did not... 
fixed release should be up now [here v3.14.5](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.14.5)

![grafik](https://user-images.githubusercontent.com/52826614/222963481-e4af4adc-2070-481d-90c7-9883dbabe964.png)

**Comment by Akamaru** [comment] 2023-03-05 14:33
It's working now, thank you!


![crd](https://img.ponywave.de/images/2023/03/05/Crunchyroll_Downloader_2023-03-05_15-31-17.png)

**Comment by Akamaru** [comment] 2023-03-06 12:42
Ok, I have another question. Can you add support for artists links, like the series links?
Example https://www.crunchyroll.com/artist/MA78053FF6/claris

**Comment by hama3254** [comment] 2023-03-08 16:44
It should be possible but i don't think i will do that.
The [add-on for chrome](https://github.com/hama3254/CRD-add-on/releases/tag/v0.6.2) does already work for me so this should be good enough.
![grafik](https://user-images.githubusercontent.com/52826614/223773939-33908224-6b5d-41c9-8e7a-1dac51e20336.png)

**Comment by AlexanderReyes023** [comment] 2023-03-12 04:46
![Uploading 20230311_224044.jpg…]()
Porqué sale este error

**Comment by hama3254** [comment] 2023-03-12 10:43
@AlexanderReyes023 i can not see the screenshot, please retry to upload the image.

**Comment by AlexanderReyes023** [comment] 2023-03-12 12:55
![20230311_224044](https://user-images.githubusercontent.com/124371164/224546018-6a90a99b-8725-477c-bc7c-aefded841200.jpg)

**Comment by hama3254** [comment] 2023-03-12 14:03
@AlexanderReyes023 You don't have permisson to open a subprocess.
This can happen due to missing permissons, i would suggest to not save the downloader directly on the `C:\` path or `C:\Program Files` due to windows permission issues.
I would put it inside the documents folder of your windows.

**Comment by janiacteia** [comment] 2023-03-16 01:09
![image](https://user-images.githubusercontent.com/16007846/225483743-f3e52717-9459-4201-afe6-de3bee10caf1.png)
erro

**Comment by janiacteia** [comment] 2023-03-16 01:13
when that happens I have to wait a while until it works normally again

**Comment by hama3254** [comment] 2023-03-16 06:00
@janiacteia the fact that it fixes itself indicates that it is caused by invalid data from CR which than triggers poor error handling of the downloader.

**Comment by janiacteia** [comment] 2023-03-16 18:17
@hama3254 yes, they limit the amount of download "SONY damn"

**Comment by janiacteia** [comment] 2023-03-16 18:19
but I have another problem, when downloading a video that has several languages together, sometimes it doesn't download in my language "Portuguese" I have to go to the episode and change the language and get the link "that looks different"

**Comment by hama3254** [comment] 2023-03-16 20:14
@janiacteia every CR video has a unique id which also determines the Dub language, the ids of the alternativ versions are avalible inside the api but the setting is not applied to it so it always defaults to the input urls dub.

**Comment by hama3254** [comment] 2023-03-19 18:36
musicvideos/concerts seem to work fine enough so i will close this.

**Closed by hama3254** 2023-03-19 18:36 UTC

**Comment by GHCripto** [comment] 2023-06-24 06:39
I know the topic is already closed but for some reason it doesn't work for me, I just can't download music videos.
When entering the link, after 30 seconds a message appears saying "Nothing found".
So, is it not possible to download music videos or concerts anymore or was this option disabled until a future update?
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/64995694/fccf90bd-c59a-4e28-b040-551419613120)

**Comment by Luis41295** [comment] 2023-06-25 17:26
> I know the topic is already closed but for some reason it doesn't work for me, I just can't download music videos. When entering the link, after 30 seconds a message appears saying "Nothing found". So, is it not possible to download music videos or concerts anymore or was this option disabled until a future update? ![image](https://user-images.githubusercontent.com/64995694/248449155-fccf90bd-c59a-4e28-b040-551419613120.png)

i'm too get this error
