### ISSUE TITLE
get url in funimation

### ISSUE THREAD

**Issue by feren6190** [hama3254/Crunchyroll-Downloader-v3.0#311] opened 2021-07-03 13:01 UTC
when you tried to download this message appears
![Captura](https://user-images.githubusercontent.com/86535486/124355043-d51e1400-dbd4-11eb-945f-ac5fecb548bb.JPG)
![Captura2](https://user-images.githubusercontent.com/86535486/124355046-d8190480-dbd4-11eb-9a16-707999f6c234.JPG)

**Comment by feren6190** [comment] 2021-07-03 13:08
![Captura3](https://user-images.githubusercontent.com/86535486/124355249-cb48e080-dbd5-11eb-9a8c-333d23366d6f.JPG)

**Comment by hama3254** [comment] 2021-07-03 16:08
> 
> 
> ![Captura3](https://user-images.githubusercontent.com/86535486/124355249-cb48e080-dbd5-11eb-9a8c-333d23366d6f.JPG)

this means you need to login inside the downloader with a premium account since there is no free version for your selected Episode/Dub

**Comment by feren6190** [comment] 2021-07-03 16:15
if I have a premium account but it won't let me download
![Captura4](https://user-images.githubusercontent.com/86535486/124360519-f8a28800-dbef-11eb-9fe7-cfb9e7acb60d.JPG)

**Comment by hama3254** [comment] 2021-07-04 13:38
i think i found the issue for the premium episode, the cookie was only saved for use if the old side was detected.
The next version should fix that and for the first error i improved the Json parsing which should reduce the issue.

**Comment by hama3254** [comment] 2021-07-04 15:34
please try [Crunchyroll-Downloader-v3.8-Beta-U11.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/download/v3.8-Beta/Crunchyroll-Downloader-v3.8-Beta-U11.zip) and see if is solves your issues.

**Comment by feren6190** [comment] 2021-07-05 01:12
Thank you you are great ^^

**Comment by MauricioElgueta2000** [comment] 2021-07-05 05:40
I tried the new version and I get this 
![Captura de pantalla (21)](https://user-images.githubusercontent.com/86944815/124422861-02cc9f80-dd32-11eb-9b93-6bc3ffedc944.png)

**Comment by MauricioElgueta2000** [comment] 2021-07-05 05:41
I am logged into my account
![Captura de pantalla (20)](https://user-images.githubusercontent.com/86944815/124422921-242d8b80-dd32-11eb-91cc-571cf413a0b6.png)

**Comment by hama3254** [comment] 2021-07-05 08:27
@MauricioElgueta2000 well is hard to say where the issue is there, what you can try is to keep the build-in browser open and try it again.
The browser should navigate to the website and then you should see if it gets the new funimation website or the old one.
The new one should look like the bottom of the screenshot below :
 ![grafik](https://user-images.githubusercontent.com/52826614/122682463-c3fafd80-d1f9-11eb-9fc2-631c7741d342.png)

**Comment by MauricioElgueta2000** [comment] 2021-07-05 21:00
it does not work even with the built-in browser open. 
![Captura de pantalla (23)](https://user-images.githubusercontent.com/86944815/124517629-6dbdbb00-ddb2-11eb-821e-c03877f4e26c.png)
 Also, how to make the extension work, it doesn't work for me

**Comment by hama3254** [comment] 2021-07-06 03:50
@MauricioElgueta2000 the add-on needs to enabled in the settings by selecting a port either from the drop-down menu or by writing one into the main box of drop-down.
I need also to mention that U11 has a major issues and it should be upgraded to U12 which also could fix your issue.

**Comment by MauricioElgueta2000** [comment] 2021-07-06 17:58
ok, I'm going to try the new version to see how it works for me.

**Comment by MauricioElgueta2000** [comment] 2021-07-08 23:41
@hama3254 With the extension I managed to download without any problem, but if I do it in a normal way sometimes it works and in others it gets stuck, but the extension works well there is no problem.

**Comment by hama3254** [comment] 2021-07-10 10:33
> @hama3254 With the extension I managed to download without any problem, but if I do it in a normal way sometimes it works and in others it gets stuck, but the extension works well there is no problem.

Thanks for the feedback about the add-on, it nice to hear something is working usually i only get complains. 
for the issue with the normal way is there any pattern on which point it failes or get stuck?

**Comment by feren6190** [comment] 2021-07-11 02:31
why when I want to download many episodes I feel and in some videos I get only 300 megs of downloads
https://user-images.githubusercontent.com/86535486/125180964-e8794280-e1c5-11eb-9765-f784a6972755.mp4

**Comment by feren6190** [comment] 2021-07-11 02:40
https://user-images.githubusercontent.com/86535486/125181143-7570cb80-e1c7-11eb-9eea-83019f5fe768.mp4

**Comment by feren6190** [comment] 2021-07-11 02:44
https://user-images.githubusercontent.com/86535486/125181186-f203aa00-e1c7-11eb-9b81-e39bab05204e.mp4

**Comment by feren6190** [comment] 2021-07-11 02:49
https://user-images.githubusercontent.com/86535486/125181257-c33a0380-e1c8-11eb-856e-67e7749b55a9.mp4

**Comment by hama3254** [comment] 2021-07-11 10:45
videos are not the best way to give me information in such cases, i don't see your settings which has an impact on the size.
you also need to keep in mind that the displayed size is the final size not the downloaded data.
to help me with determinant what's going on there please add the log files, you can get them by right clicking on the download itself and either "copy log to clipboard" or "save log to file".

**Comment by MauricioElgueta2000** [comment] 2021-07-13 16:27
@hama3254 I tried to download normally but now I get the video not found message, but the extension works fine, no problem.

**Comment by hama3254** [comment] 2021-07-13 16:52
@MauricioElgueta2000 that's a little bit vague since they not only changed the appearance of the overview but also made a complete new JavaScript based site which loads everything it needs after the page itself has loaded.
The old grabber for funimation checks for certain elements in the website and with the new website there are just not there so the old version which i can not remove because it's still in use and users can switch without even noticing like here it switched  from "funimation.com" to "js" which means the code that was executed was completely different based on what you give the downloader.
<details>
  <summary>Image</summary>

![grafik](https://user-images.githubusercontent.com/52826614/125492665-f1d61620-7d6b-420e-ab99-d05160a77536.png)

</details>

if you get the "Status: no video found" issue then please click on the line on the bottom of the downloader it opens the debug log, you can copy/pate the text from there that gives me the most useful information possible.

![grafik](https://user-images.githubusercontent.com/52826614/125493287-415418f9-303a-4bba-a646-661fc6937459.png)

**Comment by MauricioElgueta2000** [comment] 2021-07-13 16:57
@hama3254 Sorry for not being more specific with the problem of normal downloading, there is no problem in downloading one by one, the problem arises when trying to download several episodes as well as a complete season of 12 episodes.

**Comment by 619beave** [comment] 2021-07-13 18:20
Unable to log into Funimation, it is either stuck on Enter your Login Name and password or just do nothing.

Also, the Firefox browser is having problems loading the CrunchyRoll Beta homepage on my end as well.

**Comment by hama3254** [comment] 2021-07-25 10:32
with the login issue the gecko version is very limited anyway for funimation.
i close this now for everything concerning  funimation you most likely need the chromium version anyway and for that please refer to issue #321 or the release disscussion #326

**Closed by hama3254** 2021-07-25 10:32 UTC
