### ISSUE TITLE
No video found in funimation

### ISSUE THREAD

**Issue by kanohn** [hama3254/Crunchyroll-Downloader-v3.0#357] opened 2021-09-16 01:46 UTC
Hi,

I've been using the crunchyroll downloader these days without any problem..

Today i tried to download some episodes from funimation, and i have tried with 3 different animes. All trys results with "no video found" and don't download...

Could someone confirm that? I tried with The last Chromium and 3.8 version with Chrome add-on..
And yes, my premium is still active!

**Comment by hama3254** [comment] 2021-09-16 05:01
I need to take a look at it after work but in the past account issues had different errors (mature content warning or no free experience message).
You could check if your Url works in your normal Webbrowser since they had a different version of the episode page that was loaded mostly with JavaScript and that did not work for me in any way neither inside the normal browser or the downloader.
The difference could be seen by the Url, the JavaScript version did not have the language inside the url like `...com/shows/...` and not  `...com/en/shows/...`

**Comment by kanohn** [comment] 2021-09-16 13:49
Yes, it works on my normal browser, i can watch the episode, however if i try to download it on the downloader, its not find the video..

The url that its getting: javascript:https://www.funimation.com/v/full-dive-this-ultimate-next-gen-full-dive-rpg-is-even-shittier-than-real-life/vrreality

And it works on normal browser..

No matter what anime i try, no ones works..

I will wait you test yourself.. thanks!

**Comment by hama3254** [comment] 2021-09-16 14:59
> The url that its getting: javascript:https://www.funimation.com/v/full-dive-this-ultimate-next-gen-full-dive-rpg-is-even-shittier-than-real-life/vrreality

i am not sure what that means, the add-on only adds the `javascript:` tag to allow the item to be selected on the website and the downloader needed a marker where the next url starts so that `javascript:` tag is used there as well but while doing that it gets removed from the url.
![grafik](https://user-images.githubusercontent.com/52826614/133632293-932f1bec-9dba-4036-9396-f91ab7d05ada.png)

the download itself works fine even tho it fails to load the video on the new website itself
![grafik](https://user-images.githubusercontent.com/52826614/133633390-73bc0b2b-3c6b-4215-91c7-c85548d40804.png)

**Comment by 619beave** [comment] 2021-09-16 16:35
I am also getting this error as well.
![Screenshot 2021-09-16 09 04 37](https://user-images.githubusercontent.com/41927382/133651040-47dbb929-e5ad-41bf-87a3-7f1c418460a1.png)

**Comment by hama3254** [comment] 2021-09-16 16:42
> 
> 
> I am also getting this error as well.
> ![Screenshot 2021-09-16 09 04 37](https://user-images.githubusercontent.com/41927382/133651040-47dbb929-e5ad-41bf-87a3-7f1c418460a1.png)

please add your version number, this should be already fixed.

**Comment by hama3254** [comment] 2021-09-16 20:28
The main issue is that they new `/v/` sites instead of the old ones and there seems to be issues with the processing of that new site.
It seems there are some minor changes for a proper path generator.
 
`16.09.2021 22:16:30 -allowed_extensions ALL -i "E:\\CRD-Temp-File-KegUIFQSDaNZTXJH\Stream-0\index.m3u8" -allowed_extensions ALL -i "E:\\CRD-Temp-File-KegUIFQSDaNZTXJH\Stream-1\index.m3u8" -metadata:s:a:0 language=eng  -c:v hevc_nvenc -preset fast -b:v 4000k -c:a copy -bsf:a aac_adtstoasc "E:\TestFull Dive: This Ultimate Next-Gen Full Dive RPG Is Even Shittier than Real Life! Season 1 Episode 1.mkv"` 

windows also does not like the second `:` as it seems...
![grafik](https://user-images.githubusercontent.com/52826614/133680722-1c245078-798b-415e-ad69-fde0aa06a422.png)

i will work on that mean while you could try the old site for that you need to change the `/v/` to `/en/shows/` like :
`https://www.funimation.com/v/full-dive-this-ultimate-next-gen-full-dive-rpg-is-even-shittier-than-real-life/vrreality`
to
`https://www.funimation.com/en/shows/full-dive-this-ultimate-next-gen-full-dive-rpg-is-even-shittier-than-real-life/vrreality/`
that seems to work for now. 
![grafik](https://user-images.githubusercontent.com/52826614/133681360-913b42c9-a79a-464d-bf82-4905251d057e.png)

**Comment by 619beave** [comment] 2021-09-16 20:47
Changing the "/v/" to "/en/shows/" works.

Thanks for the input and your great work and your attention to detail.

**Comment by kanohn** [comment] 2021-09-16 23:31
Could the addon of chrome be updated with this fix for older urls for now? i'm using addons instaed of new Chromium because sometimes this new version crashs for me..

thanks for the work!

**Comment by hama3254** [comment] 2021-09-17 04:20
> Could the addon of chrome be updated with this fix for older urls for now? i'm using addons instaed of new Chromium because sometimes this new version crashs for me..
> 
> thanks for the work!

This is just a temporary workaround and you can also change the url inside Webbrowser and then add the single episode.
The older version also don't get updated anyway so if you have issues with the new one please report them properly.
This is inconvenient but i can help any better with the limited time and the error report where not exactly precisely, i mean it worked until they used the /v/ episode page so that would be nice to know since i have bookmarks for a view episodes to test and the old thing still works ...

**Comment by NatsuFT36** [comment] 2021-09-17 14:02
Hi, the site began to update its page on September 15 with a player like Animelab and Nintendo Switch; and that was seen in the broadcast chapters and those who are uploading the dubbing using the "/v/" instead of "en/show" or "es-mx/show" but they will update it until it completes in October

**Comment by hama3254** [comment] 2021-09-20 19:47
i uploaded a version that should fix the issue of the invalid path of the /v/ urls.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x
that what i tested worked but that was just two times the same episodes with different dub settings and other naming option.
![grafik](https://user-images.githubusercontent.com/52826614/134065377-6457d83b-47c2-45d9-9679-3eb03916840c.png)

**Comment by kanohn** [comment] 2021-09-21 11:51
Thanks! We'll test properly!

**Comment by kanohn** [comment] 2021-09-22 16:16
I tried to download some episode but i got: Checking Traffic - 10, -9, -8, etc..
got - 0 and don't download nothing..
https://ibb.co/Qn4LL5x

**Comment by hama3254** [comment] 2021-09-22 16:28
The mass downloader is not working since they have a completed new 

>due to changes on the funimation website the downloader is not fully functional currently this includes the mass downloader and everything with the new `/v/` in it's urls. 
i am working on that but they have new JSON format which mean i have to rewrite the whole mass download selection.

Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/359#issuecomment-922003311

**Comment by 619beave** [comment] 2021-09-22 16:35
I am getting the same error as kanohn.  Still works with the edit from /v/ to /en/shows/

**Comment by kanohn** [comment] 2021-09-22 20:47
I tried with mass downloader and only 1 video, both got this error..

i did not try changing /v/ to /en/shows on this version

**Comment by hama3254** [comment] 2021-09-23 04:52
I would need the debug log from the bottom of the Downloader to see what's wrong there.
Just click on the bottom bar then you should get that log.
This is a normal text field so you can just copy it from there.
![grafik](https://user-images.githubusercontent.com/52826614/133632293-932f1bec-9dba-4036-9396-f91ab7d05ada.png)

**Comment by 619beave** [comment] 2021-09-23 12:07
Here's mine:
Web server started at: 127.0.0.1:8080
Start loading: 9/23/2021 5:06:03 AM
get html
9/23/2021 5:06:04 AM.126
https://www.funimation.com/v/higurashi-when-they-cry-gou/episode-13-d2bf0056-1258-11ec-9d98-0242ac110003?lang=english
https://title-api.prd.funimationsvc.com/v1/shows/higurashi-when-they-cry-gou/episodes/episode-13-d2bf0056-1258-11ec-9d98-0242ac110003/?region=US&deviceType=web&locale=en
https://title-api.prd.funimationsvc.com/v1/videos/2281751/play?region=US&deviceType=web
3
processing :https://title-api.prd.funimationsvc.com/v1/shows/higurashi-when-they-cry-gou/episodes/episode-13-d2bf0056-1258-11ec-9d98-0242ac110003/?region=US&deviceType=web&locale=en
https://title-api.prd.funimationsvc.com/v1/shows/higurashi-when-they-cry-gou/episodes/episode-13-d2bf0056-1258-11ec-9d98-0242ac110003/?region=US&deviceType=web&locale=en
error- getting v1Json data
System.Net.WebException: The server committed a protocol violation. Section=ResponseHeader Detail=CR must be followed by LF
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Crunchyroll_Downloader.Main.GetFunimationJS_Video(String v1JsonUrl, String v1JsonData) in D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0 - CefSharp\Crunchyroll Downloader\Main.vb:line 4724
https://title-api.prd.funimationsvc.com/v1/shows/higurashi-when-they-cry-gou/episodes/episode-13-d2bf0056-1258-11ec-9d98-0242ac110003/?region=US&deviceType=web&locale=en
get html

**Comment by hama3254** [comment] 2021-09-23 20:02
The error handling was not working due to an invalid check inside the processing. 
this should be fixed with [Crunchyroll-Downloader-Chromium-Hotfix-357_1](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)

**Comment by 619beave** [comment] 2021-09-23 20:32
Confirmed working now.

Thanks!

**Comment by kanohn** [comment] 2021-09-24 14:06
Hi..

I have tested the new version hotfix 357_1 today, and got crash when tried to download 1 video..
I tried this video link: https://www.funimation.com/v/scarlet-nexus/the-hospitals-secrets

The status changed to "checking traffic -10,-9,etc..", after "looking for video" and "video found!".

After "video found" got this crash:
https://ibb.co/8NZ4ybV

Program Log:
https://pastebin.com/LgAgPGCt

**Comment by hama3254** [comment] 2021-09-24 16:36
The closest file access is the subtitle error log which not get created for me with english as setting and since you tried Dub anyway i would recommitment disabling subs for that. 
![grafik](https://user-images.githubusercontent.com/52826614/134709825-40517f7b-d254-4ab7-bb26-7822e006ddcb.png)

and i can not check for portuguese DUB (Geo blocking and premium requirement) and english works fine.

![grafik](https://user-images.githubusercontent.com/52826614/134709161-d5594cbe-d115-4f78-84f9-ce96e7b480c9.png)

**Comment by hama3254** [comment] 2021-09-26 19:59
i uploaded [Crunchyroll-Downloader-Chromium-Hotfix-357_2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x) which should re-enable the mass download from funimation

**Comment by hama3254** [comment] 2021-09-28 04:17
> On the version 357_2 i still get crashes.. on 357_1 crashes on dub portuguese with subtitle, that when i disabled it worked, however on 357_2 i got crash even if i disable it.
> 
> https://postimg.cc/4HGxQyXx
> https://pastebin.com/s3wqxUvc

It is still the same issue as we had many times before just with an old request that worked that was since i added Funimation.

>System.Net.WebException: The server committed a protocol violation. Section=ResponseHeader Detail=CR must be followed by LF

The server just sends an invalid answer to a valid request, the only way I can fix that is by cutting the function there and make the request if it fails i need to load it with the browser and process everything after that inside a new function.

**Comment by hama3254** [comment] 2021-10-09 09:17
it's already fixed and [Crunchyroll-Downloader-Chromium-Hotfix-357_3](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x) has been uploaded.

**Comment by psjmaster** [comment] 2021-10-10 13:24
Hello hama3254, how are you? First of all I would like to thank you for your excellent work.
I'm using Crunchyroll-Downloader-Chromium-Hotfix-357_3 version, and still I can't download some titles, I get the following error:
![2021-10-10_102153](https://user-images.githubusercontent.com/82722739/136697638-67a426cd-36b9-4690-983c-79126ebac543.jpg)

Would it be possible to help with this? Thanks!

**Comment by hama3254** [comment] 2021-10-10 16:00
> 
> 
> Hello hama3254, how are you? First of all I would like to thank you for your excellent work. I'm using Crunchyroll-Downloader-Chromium-Hotfix-357_3 version, and still I can't download some titles, I get the following error:
> 
> ![2021-10-10_102153](https://user-images.githubusercontent.com/82722739/136698209-bc2be6c1-7c18-4a94-8a84-022045b6deba.jpg)
> 
> Would it be possible to help with this? Thanks!

you need to add more information otherwise i can impossible check what's wrong with what show on which settings.

**Comment by janilssonn** [comment] 2021-10-10 16:08
https://user-images.githubusercontent.com/16007846/136704005-61b8cf3c-d4d4-4ab5-bcf5-18eaec92f84b.mp4

same mistake

**Comment by janilssonn** [comment] 2021-10-10 16:11
I have another problem that when downloading video from Crunchyroll the audio locks up in parts of the video, I've tried all versions and it still continues

**Comment by hama3254** [comment] 2021-10-10 17:24
@janilssonn the only issue i can see it the mature content filter 
![grafik](https://user-images.githubusercontent.com/52826614/136706565-f4e66e93-7009-45d4-a50b-cf12779583b6.png)
![grafik](https://user-images.githubusercontent.com/52826614/136706570-5102ec61-d393-4516-ba2b-d38753145c8c.png)

**Comment by janilssonn** [comment] 2021-10-10 18:20
I hadn't specified the language even though I put what I want to download. :/

**Comment by hama3254** [comment] 2021-10-10 18:37
> 
> 
> ![image](https://user-images.githubusercontent.com/16007846/136708351-f0a1976d-fc87-4f15-8c7f-07e8b5f66832.png)

this is not an downloader issue, you simple need a premium account for that

**Comment by janilssonn** [comment] 2021-10-14 02:21
i'm sorry hama but i can't download anything from Funimation and i have a serious problem with syncing audio (pt-br) with videos from CR, i've tried all versions but i can't, and its fix didn't work still freezes the program and it becomes unusable, sorry, I can't help but I'm a big fan of your program and of you!

**Closed** 2021-10-17 11:02 UTC
