### ISSUE TITLE
Can't Download Anything [System.exception error - getting culr: (60) SSL certificate problem]

### ISSUE THREAD

**Issue by psjmaster** [hama3254/Crunchyroll-Downloader-v3.0#795] opened 2023-08-05 12:09 UTC
**Describe the bug**
Hello everything is fine? I am no longer able to download. I have a premium account and when I try to download I get this Screenshots error. Could you please help me with this error?

**Where does the issue happen?**
 - Platform: [Crunchyroll Premium]
 - Settings [any configuration i get the same error]
 - Version [I tested the versions: Crunchyroll-Downloader-v3.15.4 ; Crunchyroll-Downloader-v3.15.5 and Crunchyroll-Downloader-v3.15.6 and in all I get the same error]

**Screenshots**
![error](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/82722739/9ea893f0-f1d5-470e-bf7a-974b6694852b)

**Additional context**
I tried to download several different videos and I get the same error

**Comment by bybpow** [comment] 2023-08-05 16:55
Before going further. Are you logged in the browser?

**Comment by psjmaster** [comment] 2023-08-05 17:50
Hello, yes I'm logged in the browser

Em sáb., 5 de ago. de 2023 às 13:55, Ruben ***@***.***>
escreveu:

**Comment by bybpow** [comment] 2023-08-05 18:02
I have no problems. Can you share an URL as an example?

**Comment by psjmaster** [comment] 2023-08-05 18:24
Yes, here is an example url:

https://www.crunchyroll.com/pt-br/watch/GX9UQZEZJ/premature-death?modal=restricted&referrer=cap_cr_carousel_2_jujutsu-kaisen_pt&utm_campaign=jujutsu-kaisen_pt&utm_medium=carousel_2&utm_source=cap_cr



[image: image.png]


If you need any other information just say ok


Em sáb., 5 de ago. de 2023 às 15:02, Ruben ***@***.***>
escreveu:

**Comment by psjmaster** [comment] 2023-08-05 18:28
Hello friend, I apologize for the inconvenience. After your information
that you are not having any problem I decided to disable the ativirus and
found out that for some reason it was causing the problem

Em sáb., 5 de ago. de 2023 às 15:23, Paulo Sergio ***@***.***>
escreveu:

**Comment by psjmaster** [comment] 2023-08-05 18:29
I deleted the post I made so as not to cause confusion for other users

Em sáb., 5 de ago. de 2023 às 15:28, Paulo Sergio ***@***.***>
escreveu:

**Comment by bybpow** [comment] 2023-08-05 18:46
> Hello friend, I apologize for the inconvenience. After your information that you are not having any problem I decided to disable the ativirus and found out that for some reason it was causing the problem

Some people seem to have that problem. Not my case. Glad I was useful.

**Comment by hama3254** [comment] 2023-08-07 05:50
> disable the ativirus and found out that for some reason it was causing the problem

I know some anti virus did put themselves into the encrypted connection with there own certificate.
I know this form this old German YouTube video :
https://youtu.be/_odqJyMLSd0

I personally would not recommend to use any 3rd party anti virus because windows 10 has alredy the Defender which should be enough for private people.

**Comment by Sacred-Shadow** [comment] 2023-08-09 19:05
Bei mir ist das Problem erst mit der neusten Version entstanden. 
Als ich noch mit ner niedrigeren 3.15.x unterwegs war ging es. 

AVG Internet Security klemmt sich in die SSL Verbindung.
Auch Ausnahme und Co. funktioniert nicht - man muss es abschalten. 

@hama3254 kann man curl nicht noch sagen, er soll einfach jedes Zertifikat akzeptieren?

**Comment by hama3254** [comment] 2023-08-10 08:04
@Sacred-Shadow der downloader hat die [--insecure](https://curl.se/docs/manpage.html#-k) option von curl drinnen :

> 3\. add the insecure option
>         ![image](https://user-images.githubusercontent.com/62562341/258601506-3b676944-8c21-4608-9355-084b05cab587.png)

**Comment by Sacred-Shadow** [comment] 2023-08-10 08:13
Joar, die hab ich auch aktiv .. wirkt da aber nicht. :D

**Comment by hama3254** [comment] 2023-08-13 13:41
@Sacred-Shadow dann bleibt dir wohl nicht anderes übrig als deinen AV zu deaktivieren (oder gleich deinstallieren :|) 

For everyone else the issue is resolved (or for once not my faul) so i think i can close this.

**Closed by hama3254** 2023-08-13 13:41 UTC
