### ISSUE TITLE
CR Downloader does not work with Crunchyroll Beta

### ISSUE THREAD

**Issue by pruebark9** [hama3254/Crunchyroll-Downloader-v3.0#511] opened 2022-07-26 18:22 UTC
As of today, CR has updated its website to the beta version and the CR Downloader has stopped working T_t

I have the latest version.

**Comment by hama3254** [comment] 2022-07-26 19:24
For me i still get the old website as long as i am not logged in and as soon as i logg in everything works as usual 
![grafik](https://user-images.githubusercontent.com/52826614/181094534-1ab7e0fa-4430-4eb3-8a20-914b6cc2a859.png)

**Comment by pruebark9** [comment] 2022-07-26 19:30
Strange, it doesn't work for me. It stays in "loading" and does not start downloading.

I have tried to put the URL of before (https://www.crunchyroll.com/es-es/dropkick-on-my-devil/episode-4-how-to-have-a-wicked-time-in-jinbocho-852542) as the one of now (https://beta.crunchyroll.com/es-es/watch/GWDU8WM9J/how-to-have-a-wicked-time-in-jinbocho) and nothing, it always stays in loading.

**Comment by bellydelph1** [comment] 2022-07-26 20:53
I'm also having this problem. You can solve by putting the series link and not the episode link. See the example:

- If u put the episode link, it's just loading.. the link 
(https://beta.crunchyroll.com/pt-br/watch/GG1U2QK99/sorcerer-kingdom-ains-ooal-gown-ains-ooal-gown-nation-of-leading-darkness)

- Putting the series link and choosing the season and episode in the program.. the link 
(https://beta.crunchyroll.com/pt-br/series/G69PZ5PDY/overlord)

![Sem título](https://user-images.githubusercontent.com/76275714/181109651-6d899fb7-6d05-45cd-9cde-9f1b3fe2ab2c.png)

**Comment by pruebark9** [comment] 2022-07-26 21:44
> I'm also having this problem. You can solve by putting the series link and not the episode link. See the example:
> 
> * If u put the episode link, it's just loading.. the link
>   (https://beta.crunchyroll.com/pt-br/watch/GG1U2QK99/sorcerer-kingdom-ains-ooal-gown-ains-ooal-gown-nation-of-leading-darkness)
> * Putting the series link and choosing the season and episode in the program.. the link
>   (https://beta.crunchyroll.com/pt-br/series/G69PZ5PDY/overlord)
> 
> ![Sem título](https://user-images.githubusercontent.com/76275714/181109651-6d899fb7-6d05-45cd-9cde-9f1b3fe2ab2c.png)

Thanks for the answer but it still does not work for me. I put the link to the anime itself and nothing happens.

**Comment by hama3254** [comment] 2022-07-27 07:13
> . It stays in "loading" and does not start downloading.

That would indicate that CR might serve you an invalid site like the just the homepage, this usually happens if you don't have access to the beta website but try do access it.
If you are using an account inside your Webbrowser then you need to also login inside the build-in Webbrowser of the downloader to get the same access level.

**Comment by hama3254** [comment] 2022-07-27 07:17
> I'm also having this problem. You can solve by putting the series link and not the episode link. See the example:

I don't know how this should change anything since the downloader just looks the url up itself but it should be the exact same as the one you get from CR yourself.

**Comment by pruebark9** [comment] 2022-07-27 09:59
Of course I am logged into the CR Downloader browser. I logged out and logged in again and nothing, it still doesn't work T_T

**Comment by Lynacchi** [comment] 2022-07-27 13:15
Since I was forced to switch to beta yesterday, it no longer works for me either. And the latest version of CRdl doesn't change that at all. It is always "loading..." whether the episode is selected directly or by selecting the show.

**Comment by Lynacchi** [comment] 2022-07-27 16:15
@hama3254 Yes and I have also accepted all cookies (if this is relevant)

**Comment by pruebark9** [comment] 2022-07-27 16:35
A small note, the last published version works but the download is slow, it does not go over 5MB. On the other hand, testing the 3.8.8.1 also works but in this version it downloads much faster (10-20MB).

**Comment by hama3254** [comment] 2022-07-27 17:11
> A small note, the last published version works but the download is slow, it does not go over 5MB. On the other hand, testing the 3.8.8.1 also works but in this version it downloads much faster (10-20MB).

@pruebark9 do you have the add-on support enabled inside the settings? if so try disabling it and see it that makes it better

**Comment by pruebark9** [comment] 2022-07-27 17:26
> > A small note, the last published version works but the download is slow, it does not go over 5MB. On the other hand, testing the 3.8.8.1 also works but in this version it downloads much faster (10-20MB).
> 
> @pruebark9 do you have the add-on support enabled inside the settings? if so try disabling it and see it that makes it better

I just tested it and no, it remains the same by deactivating the plugin.

**Comment by Lynacchi** [comment] 2022-07-27 17:40
After I deleted the CRD Profiles folder, it works again. Apparently the error was hidden there. My problem has now been solved.

However, I have to agree with pruebark9 at this point that the download is really slow. I was able to download at up to 100 MB/s in some cases. There were also some older titles that loaded really slowly, but symulcast were always very fast, which is no longer the case. However, I don't know if this is due to the downloader or CR.

**Comment by Lekuruu** [comment] 2022-07-27 18:03
![image](https://user-images.githubusercontent.com/84310095/181341236-29192d69-6aed-4331-b695-155eeb3be5c3.png)
When I logged in and clicked the "Check CR Beta Token" button, everything worked fine for me.

**Comment by hama3254** [comment] 2022-07-28 06:44
> ![image](https://user-images.githubusercontent.com/84310095/181341236-29192d69-6aed-4331-b695-155eeb3be5c3.png) When I logged in and clicked the "Check CR Beta Token" button, everything worked fine for me.

If you pressed `yes` on the prompt then [it should have cleared the token](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/blob/ad89b8e1a94056764576366b4a28d92207f957ee/Crunchyroll%20Downloader/Main.vb#L5306) for the API access so it will use the old network capturing method.
This might help if the token is invalid but so does a restart.

**Comment by hama3254** [comment] 2022-07-28 06:50
>I was able to download at up to 100 MB/s in some cases. 

The performance differt in the past on a per video bases.
I see what I can do but i have already trouble with supporting lower end computers because some issues can be solved by using a spacer heater as a CPU (also know as i9 12900k).

**Comment by Lynacchi** [comment] 2022-07-28 08:55
Ok, apparently only CR was super sluggish yesterday. Today everything is good again.
![Crunchyroll_Downloader-2022-07-28-10-54-34](https://user-images.githubusercontent.com/110107711/181465066-1c581694-779e-4b4a-8157-6018d3369dae.png)

**Comment by YezerSTN** [comment] 2022-07-29 19:32
I have not been able to solve it, it only says this
![image](https://user-images.githubusercontent.com/109930585/181831313-46d65044-20eb-40d2-a0aa-2a16b06f7961.png)

**Comment by hama3254** [comment] 2022-07-29 20:28
@YezerSTN please add the log file from the crashed downloader, you can [find it here](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile)

**Comment by YezerSTN** [comment] 2022-07-29 20:36
[The Slime Diaries Season 1 Episode 12.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/9223032/The.Slime.Diaries.Season.1.Episode.12.log)

**Comment by hama3254** [comment] 2022-07-29 20:41
ffmpeg seems to don't have permisson for the desktop for some reason.
`C:\Users\*****\Desktop\The Slime Diaries Season 1 Episode 12.mp4: Permission denied`
Try changing the output folder.

**Comment by YezerSTN** [comment] 2022-07-29 20:54
I tried it and it is still the same
![image](https://user-images.githubusercontent.com/109930585/181841488-bc97fee8-e89f-41b7-9433-c5b0e7fc2b9a.png)

I also receive this

![image](https://user-images.githubusercontent.com/109930585/181841626-3b35ece9-2d82-4d7a-942a-c692fb779c5f.png)

**Comment by pruebark9** [comment] 2022-07-29 21:04
> Ok, apparently only CR was super sluggish yesterday. Today everything is good again. ![Crunchyroll_Downloader-2022-07-28-10-54-34](https://user-images.githubusercontent.com/110107711/181465066-1c581694-779e-4b4a-8157-6018d3369dae.png)

What version and configuration do you have to download at that speed? I have 1000mb of fiber but it never goes over 20MB/s download. Although it always starts at 23-25MB/s but only for a few seconds, then it goes down to 5-8MB/s.

**Comment by YezerSTN** [comment] 2022-07-29 21:06
> Permission denied

`C:\Users\CEFPP\Videos\The Slime Diaries Season 1 Episode 12.mp4: Permission denied`

Same as above

**Comment by YezerSTN** [comment] 2022-07-29 21:20
Do they have anything to do with this?

![image](https://user-images.githubusercontent.com/109930585/181844550-cceaaf11-8862-4e2f-9b3c-f4a8844a5a1c.png)

**Comment by flagg19** [comment] 2022-07-30 06:28
> Do they have anything to do with this?
> 
> ![image](https://user-images.githubusercontent.com/109930585/181844550-cceaaf11-8862-4e2f-9b3c-f4a8844a5a1c.png)

With the last release, even though opening the browser I see that same error, the downloader works for me

**Comment by hama3254** [comment] 2022-07-30 06:48
@YezerSTN This is normal the browser is not able to play the video back, this has nothing to do with yout local computer and the permissions there.
![Screenshot 2022-07-30 084731](https://user-images.githubusercontent.com/52826614/181878482-9f0c4f73-b89c-401a-80d8-5870afd950ab.png)

**Comment by hama3254** [comment] 2022-07-30 08:10
> What version and configuration do you have to download at that speed? I have 1000mb of fiber but it never goes over 20MB/s download. Although it always starts at 23-25MB/s but only for a few seconds, then it goes down to 5-8MB/s.

it proably has something to do with the video itself, i also max out my 500Mbit/s Cable connection for that episode 
![grafik](https://user-images.githubusercontent.com/52826614/181880623-b72f9a2c-c67c-4627-9d84-713294ee8676.png)

one way to increase the speed would be to use more threads so i added a debug option which allows to bypass the "self estimation" of the hardware by the downloader.
[You can find the test version here:](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8.9)
![grafik](https://user-images.githubusercontent.com/52826614/181884494-f81a3370-5ec3-4da1-8cf6-1c92c44b32f4.png)

**Comment by pruebark9** [comment] 2022-07-30 12:11
Thank you for your response. I have tried setting 6 first, then 12 and finally setting the new option to the maximum and nothing, it doesn't go over 6MB/s download.

The curious thing is that version 3.8.8.1 does download more or less fast. It starts with 20-50MB/s but after a few seconds it goes down to 6-10MB/s but at least it is much faster compared to the last version.

**Comment by hama3254** [comment] 2022-07-30 13:56
Just to be clear the setting only affects download that have been added after it was changed, already running ones don't pull the new value.
The difference between v3.8.8.1 and v3.8.9 could be explained by the add-on fix since in the past due to an error the add-on part was not updating which may need some processing time.
Please also keep in mind it could be that the server has a bandwith limit during my tests `Log Horizon` was also in that 6-10MB/s range.

**Comment by pruebark9** [comment] 2022-07-30 15:32
Yes, I would make the change and add a new download to test. The weird thing is that the same episode, had different speeds in different versions.

**Comment by hama3254** [comment] 2022-08-01 13:43
The download speed has to many variables for me to help here further, it could be anything from the device you save the videos on (HDD or SSD) to network latency or just the CR server.

**Comment by MauricioElgueta2000** [comment] 2022-08-05 18:10
To me simply when it starts to download the subtitles it closes

**Comment by hama3254** [comment] 2022-08-05 18:38
> > . It stays in "loading" and does not start downloading.
> 
> That would indicate that CR might serve you an invalid site like the just the homepage, this usually happens if you don't have access to the beta website but try do access it. If you are using an account inside your Webbrowser then you need to also login inside the build-in Webbrowser of the downloader to get the same access level.

**Comment by MauricioElgueta2000** [comment] 2022-08-05 19:41
> @MauricioElgueta2000 probaste eso?
> 
> > > . Se queda en "cargando" y no inicia la descarga.
> > 
> > 
> > Eso indicaría que CR podría brindarle un sitio no válido como solo la página de inicio, esto generalmente sucede si no tiene acceso al sitio web beta pero intenta acceder a él. Si está utilizando una cuenta dentro de su navegador web, también debe iniciar sesión dentro del navegador web integrado del descargador para obtener el mismo nivel de acceso.

yes, I have the same premium account logged in in the browser and in cr downloader
![Captura de pantalla (14)](https://user-images.githubusercontent.com/86944815/183149303-ed297d82-a753-4118-b8a7-1ef3e2fbae04.png)
![Captura de pantalla (15)](https://user-images.githubusercontent.com/86944815/183149321-d40eebc8-8ed5-49eb-9d8b-3ec173a7631a.png)

**Comment by MauricioElgueta2000** [comment] 2022-08-06 08:03
> @MauricioElgueta2000 did you try that?
> 
> > > . It stays in "loading" and does not start downloading.
> > 
> > 
> > That would indicate that CR might serve you an invalid site like the just the homepage, this usually happens if you don't have access to the beta website but try do access it. If you are using an account inside your Webbrowser then you need to also login inside the build-in Webbrowser of the downloader to get the same access level.

The problem was solved, even so, I could not tell you what the cause was, since I solved it by deleting all the cr downloader files and uninstalling Microsoft Visual and downloading these 2 again and the problem was solved, although even so, thanks for being attentive to the problem.

**Comment by YezerSTN** [comment] 2022-08-15 18:19
I already solved my problem, it was not downloading because I had the antivirus (Avast). I deactivated it and now it is downloading.

**Comment by hama3254** [comment] 2022-08-17 10:11
i don't see any issue here so i close this.
if anyone has another problem feel free to make a new issue.

**Closed by hama3254** 2022-08-17 10:11 UTC
