### ISSUE TITLE
[U8]-freezing and nothing found

### ISSUE THREAD

**Issue by hama3254** [hama3254/Crunchyroll-Downloader-v3.0#575] opened 2022-10-29 13:06 UTC
The two major issues right now seem to be the application freezing and the `Status: nothing found`

[U8](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev) as an timeout added to `curl` processing which should help with the freezing.
There are also some improvents for the mutli download url constructor and the `locale` value gets tracked better from the url you use.

**Comment by hama3254** [comment] 2022-10-29 14:22
> Scheint also nun random zu sein, wann die freezes auftreten.

zufällig ist immer nicht gut, das herrrauszufinden ist immer ein problem.

> nothing found hatte ich schon mit der U7 nicht mehr

das scheint mir ein US problem zu sein den letzen kommentaren nach, das manch es nicht einfacher den fehler zu finden...

**Comment by pruebark9** [comment] 2022-10-29 17:01
Thank you for all your work.

The U7 worked without problem until, randomly, when the counter reached 0 and start downloading, said "episode found" and froze and did nothing else.

Now in the U8 it seemed that it didn't happen until, after a few times, it happened again. Another thing about the U8 is that it does not let you save the changes you make in the options, when you hit save it gives an error that gives you the option to continue or exit and in both, it does not save the changes you make.

**Comment by Serpentstar** [comment] 2022-10-29 17:03
I tried to pull the series Spy x Family.
Thread Name: Main
10/29/2022 9:44:54 AM.818
Basic bm9haWhkZXZtXzZpeWcwYThsMHE6
FrameLoadEnd10/29/2022 9:44:57 AM
get html
10/29/2022 9:44:57 AM.299
https://www.crunchyroll.com/
Just Browsing, exiting...
Start loading: 10/29/2022 9:47:10 AM
FrameLoadEnd10/29/2022 9:47:12 AM
get html
10/29/2022 9:47:12 AM.396
https://www.crunchyroll.com/series/G4PH0WXVJ/spy-x-family
LoadedUrls: 0
0
10/29/2022 9:47:23 AM Thread Name: Main
3530: nothing found

I tried to pull a single episode of Beast Tamer that I started watching in another browser an it started immediately.  Start speed was nearly instant, download speed was very poor.  For that I wonder if this has anything to do with it:
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=562706,RESOLUTION=428x240,FRAME-RATE=23.974,CODECS="avc1.42c015,mp4a.40.2"

I went to download another single episode for Villainess, it started immediately and was slow, but it started.  
While I was downloading I added another single video,  It was added the to queue.  I told it to start and once the previous video was finished, the one in the queue started.  

Single episodes seem to function without issue but are very slow.  Attempts at downloading a Series still fail.

**Comment by hama3254** [comment] 2022-10-29 17:07
> Another thing about the U8 is that it does not let you save the changes you make in the options, when you hit save it gives an error that gives you the option to continue or exit and in both, it does not save the changes you make.

U8 has no changes inside the settings and U7 only has two buttons fixed (qsv encoder options) so i have no explantion for that.

**Comment by Serpentstar** [comment] 2022-10-29 17:10
I was able to resolve my save change issue by manually clearing my CRD profile folder and choosing the option to clear all settings from the contextual menu.

**Comment by hama3254** [comment] 2022-10-29 17:16
@Serpentstar can you open the build-in webbrowser before you add a series and see if you CR displays the episode when you try to add it?

**Comment by Serpentstar** [comment] 2022-10-29 17:39
@hama3254 When I go for a series, it toggles the window in the web browser, but then goes to nothing found and stalls

**Comment by hama3254** [comment] 2022-10-29 17:46
@Serpentstar i don't quite understand, can you see the seasons/episodes within the browser like this?
The downloader is looking for the request that fills there website so if it is filled then i have to see how there are doing it without the downloader noticing.
![grafik](https://user-images.githubusercontent.com/52826614/198845748-7ad376a2-7f84-4146-a39d-882e9dc64596.png)

**Comment by Serpentstar** [comment] 2022-10-29 17:58
I think this is the easiest to explain it.
[Nothing Found.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/9894286/Nothing.Found.zip)
I used OBS to create a video of exactly what I am seeing.

**Comment by hama3254** [comment] 2022-10-29 18:52
@Serpentstar thanks, this help me to understand that the downloader does not capture that now i just need to know why.

**Comment by petenun** [comment] 2022-10-29 19:49
@Serpentstar - That is the exact behavior I'm seeing as well. Thanks for making that video to demonstrate.

**Comment by Serpentstar** [comment] 2022-10-29 20:10
@hama3254 @petenun I had found OBS just last week and was quite surprised that it is one of the apps available under the Portable Apps platform.  Seeing as it was difficult to explain where the issue was occurring, a video was the only viable solution to explaining it.  Hopefully it helps in understanding where the issue is.

**Comment by petenun** [comment] 2022-10-29 20:28
@hama3254  If you are interested in troubleshooting from within the US, I have created a virtual Hyper-V Windows 10 workstation that you can use. Just let me know and I can provide the address and credentials via Discord (since I don't think we can send DMs here).

**Comment by hama3254** [comment] 2022-10-29 21:57
i just made [U9](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev) after some quick tests with @petenun and it seems like CR loads the content sooner for you in the US then for me in Europe.
U9 does not clear the internal tracking of the apis after the website has finished load it clear it with the start of the website loading, this should catch all apis now.
U9 is a little bit untested but it's midnight for me so i just give it out for you to find all new issues this might create...

**Comment by petenun** [comment] 2022-10-29 23:02
@hama3254 Looks like great progress with U9. With my limited testing, it looks like I now get the Season / Episode selection every time now. That's great. 

The problem I see now is with moving the queued episodes to the active downloading window. Either objects don't move, or I'll get one starting to download and then the whole application locks up, requiring the process to be terminated via Task Manager. 

![2022-10-29 15_58_36-](https://user-images.githubusercontent.com/55004359/198855541-fc106ad3-a5f6-4b65-848a-17f144a83f49.png)

**Comment by Serpentstar** [comment] 2022-10-29 23:38
@petenun I just pulled the 5 episodes from Berserk and it went just fine.  Let me do a pull on Ranking of Kings.  I will edit this when I have results.  

It was nice to see that I wasn't going nuts thinking it was a Geo thing.  The only VM I have up for that are linux, so we are all lucky you had a Win10 ready.

**Comment by petenun** [comment] 2022-10-30 00:15
@Serpentstar I'm happy to help where I can, though the credit all goes to @hama3254. I do appreciate it when a group can pitch in together to help though. 

As for my earlier testing results, it appears that somehow I had lost my authentication token. Once I renewed my login, it looks like everything is downloading well, and at very good speeds.

**Comment by Serpentstar** [comment] 2022-10-30 04:52
@xILikepuddingx how many simultaneous downloads are you trying at the same time?  I have only been doing 1 and haven't had a single issue yet with U9.   But I have only processed a couple of series.  One suggestion for you however, Bring up task manager and keep an eye on the process.  I had recently encountered a memory leak and it took a while to figure out what caused it.

**Comment by MattRBX** [comment] 2022-10-30 11:41
I've had lots of problems with the other versions but so far the U9 (which is basically the same as U8 to my knowledge) seems to work just fine. I've been able to pull a couple episodes without any freezing issues and i didn't get the "nothing found" error either. 👍 

_But heres the thing._
One weird thing to take note of though is if you set your Settings > Output > Format to "mkv" and "copy" then save, reload the application to be sure it'll happen. And lastly you change it again. This time changing it to "mp4" and "merge disabled" an error pops up. The error seems fixable by simply choosing "mp4" and "mov_text" then "save and exit" reopening the settings and changing it back to "mp4" and "merge disabled" but it's a bit weird nonetheless. It's not a big issue for me in fact i only download mkv files but i thought i would point it out

**Comment by cimmy01** [comment] 2022-10-30 12:51
@Serpentstar @hama3254 So far U9 is working great I've downloaded a couple of series I have the simultaneous downloads set to 2 I am seeing some weird download speed switching for lake of a better word. the download speed when I first started was my average top speed of 900 Mbps now Im around 150-180 Mbps thats not a huge deal but its switching between one episode to another by that I mean it will download one episode at the full speed of 150-180 then stop switch to the other episode and that one will download at full speed every few seconds. I am also seeing that slow memory leak you were mentioning it seems to add a couple MB each episode and not release the finished memory. Its not a big problem as its only go up a about 30 MB or so since starting the series. The only other thing I wanted to report is the setting menu is still throwing the unhandled exceptions error and wont save the setting changes.
![Capture](https://user-images.githubusercontent.com/56510595/198879423-7485a75b-cab7-4996-a160-e640c5e7be05.PNG)

**Comment by hama3254** [comment] 2022-10-30 15:00
i have some tests and i can get it to lock up with the `Hybrid mode` if it goes to the 4th download.
this may be because of the 16 threds i use per download.
The default ffmpeg does it's thing with full 12 downloads without any issues for me.
![grafik](https://user-images.githubusercontent.com/52826614/198885343-5229f15b-b457-46a0-941c-e712acb35dd4.png)

this also means im am not able to find the issue for that here, it's running in ffmpeg mode but it still locked up.

> The problem I see now is with moving the queued episodes to the active downloading window. Either objects don't move, or I'll get one starting to download and then the whole application locks up, requiring the process to be terminated via Task Manager.
> 
> ![2022-10-29 15_58_36-](https://user-images.githubusercontent.com/55004359/198855541-fc106ad3-a5f6-4b65-848a-17f144a83f49.png)

**Comment by petenun** [comment] 2022-10-30 17:09
For those of you who are locking up during downloads, I was able to fix my issue by opening the integrated browser, logging out of Crunchyroll, and logging back on to refresh the token. Once I did that, lockups stopped for me.  I'm able to consistently download 6 streams simultaneously.

Just another thought, and this is more general troubleshooting than CRDL specific. Have you tried disabling your computer's antivirus? A lot of antivirus applications like to "touch" and inspect each file as it's written to your machine, even temporary files. Not only

**Comment by ms-ku** [comment] 2022-10-31 06:37
U9 is working for me but alwas after downloading 15-25 files CRD freezes and the task must be killed. 
In this case the files will be loaded to the end but no new ones started.
Before it worked i also had to delete the settings and the Profile Folder manually.

@hama3254 - for better troubleshooting in the future do you think it would be better to make CRD like a portable App? (App, Settings, Profile a.s.o. in one Folder). I think some Problems in the past came through old settings and Profile Folders.

Thanks for your work and greetings
msku

**Comment by rcyclope** [comment] 2022-10-31 09:16
[U9] => I have same pb when i change an option in setting
file is in french
[bug.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/9899594/bug.txt)
![Crunchyroll_Downloader_bug](https://user-images.githubusercontent.com/17126922/198973288-8f7d373e-5359-4344-abee-619a83ce5d22.png)

**Comment by hama3254** [comment] 2022-10-31 12:31
@ms-ku it may be worth a try with a portable version, [v3.9-Portable](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Portable)
i expected the `My.Settings` to write into the `Crunchyroll Downloader.exe.config` which does contain the values that are available and there default value but the .net framework (or windows) does split the settings per path to the exe and per version and saves it here: 
![grafik](https://user-images.githubusercontent.com/52826614/199006746-beb0cc47-240f-4486-8cf9-73bcf583f775.png)

this might have the downside of setting up the downloader for every release.

**Comment by ms-ku** [comment] 2022-10-31 12:59
Hallo Hama
Ich dachte ja auch nur das dies evtl. ein Ansatz zum Testen sein könnte, da wären immer alle auf dem gleichen Stand. 
Mir viel das beim Umstieg von der U4 auf die U7 auf. Die U4 lief 2 Tage lang "fast" problemlos. Die U7 ging gar nicht und als ich wieder auf die U4 zurückging, ging diese auch nicht mehr.
Die paar Einstellungen neu zu setzen ist ja auch nicht viel Aufwand. Und so oft wie jetzt sollten ja keine neuen Versionen nötig sein.
Wer weiß allerdings ob CR heute Nacht wirklich nur Funktionen abschaltet und nicht evtl doch noch ein paar neue "Features" einbaut.
Evtl kannst du ja später eine Funktion einbauen, die beim ersten Starten abfrägt ob man eine portable oder stationiäre Version haben will.

@all - Sorry guys, i already written it, sometimes it is for me just better to write my native language.

Thanks for your work and greetings
msku

**Comment by ms-ku** [comment] 2022-11-01 18:46
@hama3254 
since the crunchyroll.com is available again today i have no problems with the CRD portable!!!
No freezing - meanwhile over 50 Files at the time without restart CRD!
Login date will be saved!
I would say its like before.
Thanks again for your work and greetings
msku

**Comment by HolloFox** [comment] 2022-11-06 12:28
I also get random freezes after downloading random amount of episodes. Am using U9 as well.

**Comment by hama3254** [comment] 2022-11-10 13:39
i merged the portable version into github and uploaded [`Crunchyroll-Downloader-v3.9_portable_3.zip`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Portable) this version should make a lot of improvements compared to U9.

**Comment by tormento** [comment] 2022-11-12 20:59
Can't find anything on

https://www.crunchyroll.com/it/series/GYX04955R/berserk

too.

**Comment by hama3254** [comment] 2022-11-12 21:14
@tormento i would need the data from the log at the bottom, i dont see anything wrong with it.
![grafik](https://user-images.githubusercontent.com/52826614/201494779-7bd88f64-c42a-42b3-bd09-fcf92693c1f1.png)

**Comment by tormento** [comment] 2022-11-13 09:33
@hama3254 

```
Thread Name: Main
Basic bm9haWhkZXZtXzZpeWcwYThsMHE6
Start loading: 13/11/2022 10:33:03
FrameLoadEnd13/11/2022 10:33:03
get html
13/11/2022 10:33:03.276
https://www.crunchyroll.com/it/
LoadedUrls: 0
0
13/11/2022 10:33:14 Thread Name: Main
3530: nothing found
FrameLoadEnd13/11/2022 10:33:15
get html
13/11/2022 10:33:15.834
https://www.crunchyroll.com/it/series/GYX04955R/berserk
LoadedUrls: 0
0
13/11/2022 10:33:25 Thread Name: Main
3530: nothing found
```

**Comment by tormento** [comment] 2022-11-13 13:49
With https://www.crunchyroll.com/it/series/GXJHM3P19/bocchi-the-rock

`Thread Name: Main
Basic bm9haWhkZXZtXzZpeWcwYThsMHE6
FrameLoadEnd13/11/2022 14:48:25
get html
13/11/2022 14:48:25.611
https://www.crunchyroll.com/it/
Just Browsing, exiting...
Start loading: 13/11/2022 14:48:26
FrameLoadEnd13/11/2022 14:48:27
get html
13/11/2022 14:48:27.514
https://www.crunchyroll.com/it/series/GXJHM3P19/bocchi-the-rock
LoadedUrls: 0
0
13/11/2022 14:48:37 Thread Name: Main
3530: nothing found
`

**Comment by hama3254** [comment] 2022-11-13 15:01
@tormento can you check what the browser does? 
the downloader should looks for the api request that CR uses to fill there website, the question is now does it not find the request or is it not there.
![grafik](https://user-images.githubusercontent.com/52826614/201527629-93d1ff40-a992-48fc-aca6-41714dd45ba6.png)

**Comment by tormento** [comment] 2022-11-13 15:33
It's failing to find entire seasons but It opens the season page, without finding anything to download.

The direct link to the episode works fine but when trying to download the entire season, it finds nothing.

**Comment by hama3254** [comment] 2022-11-13 15:59
For single episodes i do the API calls within the code of the downloader and only load the epiosde to look for the api call if something goes wrong.
The season download does not have this option, i only rely on the browser there to load the api while the downloader is looking for the call.
This is why it would be important to know if you see the episodes inside the buil-in webbrowser after it has loaded.

**Comment by tormento** [comment] 2022-11-13 17:06
@hama3254 when launching download with the season link, the internal browser goes to the season page. Unfortunately nothing is found to be downloaded.

**Comment by tormento** [comment] 2022-11-13 17:26
@hama3254 I tried test build too and no success.

**Comment by tormento** [comment] 2022-11-13 17:46
Ok, I tried many times and it seems to be a hit and miss. Sometimes I get season list, sometimes not.

Unfortunately, the downloader hangs during download of the first episode, that happens just after the episode selection and download command, instead of waiting for the user to click "items in queue".

P.S: In the mean time I updated curl too and it was the first time that I could, eventually, download at least the m38.

**Comment by hama3254** [comment] 2022-11-13 18:12
> @hama3254 when launching download with the season link, the internal browser goes to the season page. Unfortunately nothing is found to be downloaded.

Loading the link is fine, the question is if CR displays the episodes or not.

> Unfortunately, the downloader hangs during download of the first episode,

this has been reported but i am still unable to reproduce this as mentioned in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/578#issuecomment-1312547035

**Comment by tormento** [comment] 2022-11-13 18:25
@hama3254 as I told, I can see the episode list in the internal url but the parsing gives no results.

I have tried again a dozen of times and I can't get the playlist anymore.

**Comment by tormento** [comment] 2022-11-13 18:32
Please, if you want, have a look [here](https://github.com/Tenpi/Crunchyroll-Downloader).

It has been archived but still can download episodes with no issues.

I don't use it as downloading with ffmpeg have lead to corrupted videos sometimes. Much better your hybrid method.

**Comment by ms-ku** [comment] 2022-11-13 18:54
Hello [tormento](https://github.com/tormento)
Sorry that I didn't read everything above. 
In my case this helped

- Create a new User ( e.g. crd )
- Use Portable V2 (not v3 - with v3 i have permanent the freezing or not found problems)
- start v2 as the new user - shift right click - run as another user or console -> runas /user:"crd" /savecred "c:\........" (this is the path to Crunchyroll Downloader.exe Po_v2)

This works for me at the time - halfway but stable for a certain time.
Greetings
msku

**Comment by petenun** [comment] 2022-11-13 19:09
Not to distract from or belittle anyone's current problems, but I thought it would be worth mentioning that the 3.9 U9 is still working perfectly for me (in the US). I just wanted to reiterate so there's no assumption that it's broken for everyone. I have not tried the portable version though.

**Comment by ms-ku** [comment] 2022-11-13 19:33
You're right - I hadn't thought of that - my suggestion with Po_V2 above works for me in Germany! All other versions work worse for me.
Greetings
msku

**Comment by petenun** [comment] 2022-11-13 19:37
I'll be in Germany for the next couple weeks and will test there just to see if there is a geographical difference. I'm totally committed to international testing. [Actually, I'm going over to see family, but it sounds more impressive to say I'm going over for testing purposes.] :-)

**Comment by tormento** [comment] 2022-11-15 19:27
@hama3254 I can confirm that portable-2 can list entire seasons but it hangs during the 2nd episode download.

I have tried to enable multiple download queue but it has no effect and keeps on hanging.

Trying with 1 download maximum works but only if queue is disabled.

**Comment by hama3254** [comment] 2022-11-17 11:02
With the still unclear cause of the freezing problem inside the lastest versions i made some bigger changes to [Crunchyroll-Downloader-v3.9_portable_4.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/edit/v3.9-Portable)
This a a release from a new experimental version, the source can [be found here](https://github.com/hama3254/experimental-Crunchyroll-Downloader-v3.x)
The core change is the removal of the CefSharp Browser which has been replaced with the [WebView2 Runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section).
i also have seen a handfull of times that the log at the bottom can  block the UI so i added a timeout for the log.

**Comment by tormento** [comment] 2022-11-17 13:55
WebView2 works really well and videos can be even watched.

Unfortunately, it doesn't show the proper url to be copied:

![image](https://user-images.githubusercontent.com/2351785/202464863-4fb6bd68-4092-4a25-8432-c02e288dc0c8.png)

![image](https://user-images.githubusercontent.com/2351785/202464906-25db5063-a9af-4eb1-93cb-4891fb40a101.png)

**Comment by hama3254** [comment] 2022-11-17 16:59
> Unfortunately, it doesn't show the url to be copied, even though if you use the copy url button, it saves the correct one.

i check that and it seems that it does not count as `Navigation` so `NavigationCompleted` where it should updated is not called, i have to use `SourceChanged` ...

**Comment by MattRBX** [comment] 2022-11-22 14:27
Can someone tell me exactly what this does?
I know "merge disabled" just exports the subtitles seperately and "copy" merges them but what is this srt option exactly?

![image psd](https://user-images.githubusercontent.com/50133749/203339039-5eeec042-dcde-4981-847a-d5ad3a6bdd74.png)

**Comment by MattRBX** [comment] 2022-11-24 19:43
> normally it downloads the subtitles as ass file. ass keeps the formatting from crunchyroll. srt is a subtitle format like ass but it resets everything to standard
> 
> More: srt: https://docs.fileformat.com/video/srt/ ass: https://fileinfo.com/extension/ass ssa: https://en.wikipedia.org/wiki/SubStation_Alpha

ooh thanks i see

**Closed** 2022-11-26 11:58 UTC
