### ISSUE TITLE
Prompt to select null subtitles when subtitles not found

### ISSUE THREAD

**Issue by orroth** [hama3254/Crunchyroll-Downloader-v3.0#510] opened 2022-07-17 23:02 UTC
When subtitles are not found, a prompt is displayed asking you to select other subtitles and the combobox only contains the option null.

This prevents the queue from continuing until user interaction is performed. In this scenario (where null is the only option presented) it seems that the option null could be selected automatically (or first encounter could give the option to always apply null, or just for the rest of the session) so that the queue can continue unattended.

You could reproduce this with a series with name similar to that-time-i-got-< null >-as-a-< subtitle >

![that-time-i-got-null](https://user-images.githubusercontent.com/109116219/179428220-4091cadf-2d4f-4d87-a0a6-026f901fadd9.png)
![select-another](https://user-images.githubusercontent.com/109116219/179428222-279ea2f0-0f57-4852-ac2c-d46a51f4f0bd.png)

**Comment by orroth** [comment] 2022-07-17 23:12
It appears I can workaround by going to options for CR and selecting Hardsub language - [ null ], however, this would then need changing back to English if the series is not a Dub, so it is not a complete solution.

**Comment by hama3254** [comment] 2022-07-18 07:15
It's unusual to have just "null" like this is from shield hero Season 1 English dub and there is a stream tagged with Audio as English as you would expect but hard subs are also there as English.
![Screenshot_2022-07-18-05-57-07-02_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/52826614/179443278-6e589cfa-5b2d-4e7d-a8ee-8688ebeb5e5a.jpg)

> This prevents the queue from continuing until user interaction is performed

In other words it is as intended since there is an discrepancy between the desired video and what you can get.

> In this scenario (where null is the only option presented) it seems that the option null could be selected automatically

What if the user does not want the only available option?


> (or first encounter could give the option to always apply null, or just for the rest of the session)

Just for the session would be fine for most cases, i can see what I can do, but for always applying "null" is already a setting there as you noticed:

> options for CR and selecting Hardsub language - [ null ],

And for

> however, this would then need changing back to English if the series is not a Dub, so it is not a complete solution.

Is like you need different settings if you want to do different things 
<details>
  <summary></summary>
  
![wp5338281](https://user-images.githubusercontent.com/52826614/179461121-2b608786-942c-4ef4-9350-75bb763a15ae.jpg)

  
</details>

Using "null" with merged softsubs might also help since the downloader ignores missing softsubs files.
Please be aware that the player need to support softsubs.

**Closed** 2022-07-30 08:10 UTC
