### ISSUE TITLE
Unable to select resolution

### ISSUE THREAD

**Issue by abuseddoughboy** [hama3254/Crunchyroll-Downloader-v3.0#661] opened 2023-01-12 03:57 UTC
**Describe the bug**
When attempting to download some episodes request me to selct resolution and there are non listed, upon browsing with the browser sometimes it says its unavailable. Doesnt happen on all episodes and its more than one show.

**Where does the issue happen?**
 - Platform: Crunchyroll 
 - 3.12, 3.13

**Comment by hama3254** [comment] 2023-01-12 06:00
I have to look at this but if it's random it could come from CR.

**Comment by Serpentstar** [comment] 2023-01-12 08:19
It doesn't appear to be completely random,
![image](https://user-images.githubusercontent.com/751507/212012683-c2107ee4-58cc-4f63-ace5-fa84b6df772b.png)
![image](https://user-images.githubusercontent.com/751507/212012882-58f746b4-6711-44bf-b7be-6cb70c5282f7.png)
![image](https://user-images.githubusercontent.com/751507/212013325-ca214db2-1300-4676-9611-12595e270166.png)
![image](https://user-images.githubusercontent.com/751507/212013396-4422a6c3-2dfd-4604-9324-3859caa6301e.png)

When I see it, the error is consistent.  For example, on the series Ga-rei-Zero, I was able to download ep1 and ep3, but ep2 gives the error.  The same applies to the single episode of Kaina of the Great Snow Sea.  Error pops up every time.  Even after closing and restarting.  It feels like CR when and mucked things up again.
My resolution is 480P in hybrid mode using MKV and Copy.  I am hardcoding English subtitles with chapters.

**Comment by hama3254** [comment] 2023-01-12 15:42
It looks to me like a CR issue.
![grafik](https://user-images.githubusercontent.com/52826614/212112019-7df8c9d8-7b2a-41cc-9c9c-83458fd936cc.png)

**Comment by Serpentstar** [comment] 2023-01-12 18:56
I discovered something.  I went and changed my download resolution to 360P for Kaina of the great snow sea, and it was successful.  So there is an possibility that 480p wasn't an option.  Would it be possible to put a check in the system where if the first resolution fails, it can fall back to a smaller one?  I am going to try it on the other episode that refused to download, but I have a suspicion it will work.

**Comment by hama3254** [comment] 2023-01-12 19:32
>I discovered something. I went and changed my download resolution to 360P for Kaina of the great snow sea, and it was successful. So there is an possibility that 480p wasn't an option. 

i only the error you can see in my screenshot at the top, this mean there are no data at all or it works with every resolution.
> Would it be possible to put a check in the system where if the first resolution fails, it can fall back to a smaller one?

the drop down should let you select any available resolution but it is empy since it has no proper error handling for the case of empty or invalid data.

**Comment by todstelzer** [comment] 2023-01-13 00:24
Same problem. It's random and works after a few tries  
Maybe there should be a check in the code and when this happen wait 10s and try it 5 times and on;y give a error after 5 tries?

**Comment by AsIFall** [comment] 2023-01-13 01:05
![Screenshot (159)](https://user-images.githubusercontent.com/110290203/212212583-3e01a26e-4414-43c6-9d02-d7db489c5cef.png)
Same problem over here. I first used the version 3.9portable switched to the newly released version after the issue occured several times. I thought I need to update for the problem to be gone but it seems that it does not. Sitting here for almost half an hour trying effortly to download but with no success.

**Comment by abuseddoughboy** [comment] 2023-01-13 04:10
so when you navigate to the problem video in the built in browser it just shows a blank video, i can copy and paste the link into firefox and play the video though. I'm an idiot but is there another browser or would there be any way to identify that this app is trying to download from cr? Just trying to come up with ideas.

**Comment by hama3254** [comment] 2023-01-13 05:19
> would there be any way to identify that this app is trying to download from cr?

Not impossible but unlikely, if they want to block downloads they would use DRM which is technically difficult to crack and by doing so you would breake the law in multiple countrys.

**Comment by AsIFall** [comment] 2023-01-13 12:58
Well, it's no use it seems. The problem still occurs to me. Does not matter how often I start to try downloading the file anew. Will try with another series today.

**Comment by Akamaru** [comment] 2023-01-13 13:13
It's still working with v3.11 


![Crunchyroll_Downloader_2023-01-13_14-11-43](https://user-images.githubusercontent.com/8063440/212328126-8bd7219c-56bf-4823-abd2-b1a6e042f1e8.png)

**Comment by hama3254** [comment] 2023-01-13 13:19
Right now it will look for all 3 of the green ones and then use the first it finds.
The last git changes the code to check the next one if the request fails, this should improve the success rate.
CR would have more streams but the red ones are DRM protected and can not be downloaded, the yellow ones would just not work with the hybrid mode and the two orange ones have limited options.
![grafik](https://user-images.githubusercontent.com/52826614/212327882-b5f03673-4ca8-4355-95b9-16b7ad26dcd6.png)

**Comment by hama3254** [comment] 2023-01-13 13:25
just uploaded [v3.13.1](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.13.1) if it works as intended needs to be seen

**Comment by AsIFall** [comment] 2023-01-13 13:53
> just uploaded [v3.13.1](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.13.1) if it works as intended needs to be seen
Well, at least it does not show the missing resolution issue again.
![Screenshot (160)](https://user-images.githubusercontent.com/110290203/212335693-3f4247ec-204d-4e49-b8bc-a56b65f75e8f.png)

**Comment by hama3254** [comment] 2023-01-13 13:58
@AsIFall You can use the [`--insecure`](https://curl.se/docs/manpage.html#-k) to get around that issue 
![grafik](https://user-images.githubusercontent.com/52826614/212336638-6f598140-51e6-41d0-b889-2b9c13714e13.png)

**Comment by AsIFall** [comment] 2023-01-13 14:05
> 

Thank you. It works for me now.

**Comment by todstelzer** [comment] 2023-01-13 14:18
Hey this seems to work!
Thank you for your awesome work with this program.
Recording it with OBS is a pain... ^^; Glad it works now :)

**Comment by petenun** [comment] 2023-01-14 01:31
Seems to be working great again. Thank you @hama3254. You rock (as usual).

**Comment by Asklac** [comment] 2023-01-16 09:20
Greetings friend! I have this problem, how can I solve it?
![image](https://user-images.githubusercontent.com/67983360/212642228-1f278c37-ff00-41c8-ab93-3a5e1bad6198.png)

**Comment by stephan1978** [comment] 2023-01-18 23:19
hello 

wollte bloss sagen das die letzte folge von one piece nicht gut funktioniert nach dem download.

ab 13.30 min sind kodierungsfehler drauf (bild bleibt kurz stehen und der ton läuft nicht syncron)

gruss stephan
sonst funktioniert sehr gut

**Comment by janilssonn** [comment] 2023-01-20 17:09
I can no longer download dubbed videos CR changed her player and embedded all the audios can you fix it?

**Closed** 2023-01-21 10:33 UTC
