### ISSUE TITLE
Problem with Funimation hardsub

### ISSUE THREAD

**Issue by LexBulb** [hama3254/Crunchyroll-Downloader-v3.0#120] opened 2020-12-27 19:41 UTC
![Screenshot 2020-12-27 090722](https://user-images.githubusercontent.com/76631029/103178423-a2116580-48bd-11eb-8a28-f1e1d39fc0ef.png)
There seems to be a problem when downloading Funimation hardsub. The first problem is that the download seems to be slower compared to softsub. The second problem is only half of the video is download.

**Comment by hama3254** [comment] 2020-12-27 23:06
> The first problem is that the download seems to be slower compared to softsub

that's normal, funimation has no hardsub so they need to be post processed and without the [Nvidia NVENC](https://en.wikipedia.org/wiki/Nvidia_NVENC) encoder (which can be selected in the output settings) that takes a lot of processing power.
![grafik](https://user-images.githubusercontent.com/52826614/103180862-281bb500-489a-11eb-85e1-f937171bb897.png)

to your issue, from my test the feature works i get a 23:50min video.
the interesting thing is that the `"Finished - " + Done(0) + "MB"` line is triggered by a specific part of the output from the multimedia library `ffmpeg` which does all the work. 

If you had the logfiles enabled in the settings or saved from the context menu (only at v3.7) it would be helpful if you could add it to this issue because i have no idea why it "finished" before the end time was reached.

**Comment by LexBulb** [comment] 2020-12-28 17:27
[Uzaki-chan Wants to Hang Out Season 1 Episode 4 I Want to Hang Out Together Over the Holiday.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5748241/Uzaki-chan.Wants.to.Hang.Out.Season.1.Episode.4.I.Want.to.Hang.Out.Together.Over.the.Holiday.log)

**Comment by hama3254** [comment] 2020-12-28 18:16
Thanks for the logfile. I see what happen what got your issue but i have no idea why.
according to the logfile you have downloaded for 1 hour with a speed of `0.22x` which makes this 
> download seems to be slower

an understatement .

The issue is that after that hour it was at 13:52min then every other new fragment of that stream got the `HTTP error 403 Forbidden` response from the server.
normally this should not happen for streaming but you are 5 times slower than the normal streaming.

Unfortunately i can not do something here so i can only tell you about the `Merge soft-subs with video file` option
![grafik](https://user-images.githubusercontent.com/52826614/103234755-b9ddfd80-4940-11eb-8b52-5d51df2e64dd.png)

it is not an hardsub but it combines the subtitle into the `mp4` video file so you can select it at the most video players.

**Comment by hama3254** [comment] 2021-01-05 15:08
i guess the problem has been solved so i close this

**Closed by hama3254** 2021-01-05 15:08 UTC
