### ISSUE TITLE
The program as of today has stopped working

### ISSUE THREAD

**Issue by ZioBomba** [hama3254/Crunchyroll-Downloader-v3.0#546] opened 2022-10-19 14:04 UTC
Today crunchyroll seems to have made an update removing the "beta" subdomain, and since then the program can no longer download either subtitles or videos.

 - Platform: Crunchyroll Beta
 - Settings: Hybrid download, i try hardsub and softsubs
 - Version: 3.8.9

Screenshots:
https://prnt.sc/mpZeo7pVQ8GS

This problem happens with all anime, I've tried several but nothing, I'm not using either vpn or anything that would affect downloading

**Comment by Deseiro** [comment] 2022-10-19 14:12
I have the same problem

**Comment by pruebark9** [comment] 2022-10-19 14:16
Me too, today there was update in CR and since then it doesn't work. It seems it's something with the CR Beta token because when I give it to verify the token, it doesn't find any and gives you to put one manually.

**Comment by Revan67** [comment] 2022-10-19 14:33
Can confirm, I am unable to download anything as of today as well.

**Comment by 619beave** [comment] 2022-10-19 14:49
I also can confirm.  The beta part of the address is no longer there. 

Also, the program does not understand the address, receives an error dialog.

**Comment by MaybeAA** [comment] 2022-10-19 16:25
Yep same can't download anymore

**Comment by ET1982** [comment] 2022-10-19 16:34
mew too. the URLs removed the "beta" part and the program no longer works.

error: please make sure the URL is correct

Let's wait for the developer to fix it :-D

**Comment by MaybeAA** [comment] 2022-10-19 16:35
Guys what is the difference between ffmpeg and hybrid mode i don't understand ?

**Comment by hama3254** [comment] 2022-10-19 16:42
i am on it but there is no current time since it's not simply chaning the name because CR did something which returns the [`HTTP 403`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) status and i don't know why yet.
![grafik](https://user-images.githubusercontent.com/52826614/196751764-34dc9838-46b0-4d69-8366-7f02372c4d59.png)

**Comment by hama3254** [comment] 2022-10-19 16:46
> Guys what is the difference between ffmpeg and hybrid mode i don't understand ?

the stream not a single video but a lot of small files, ffmpeg is a video library which can download and combine all of those small files.
This does it 1 by 1 which is fine but not too fast, the hybrid mode downloads all files with more than one at he time and then ffmpeg does it job faster since the local copy is much faster to access than the online version.

**Comment by MaybeAA** [comment] 2022-10-19 16:52
> > Guys what is the difference between ffmpeg and hybrid mode i don't understand ?
> 
> the stream not a single video but a lot of small files, ffmpeg is a video library which can download and combine all of those small files. This does it 1 by 1 which is fine but not too fast, the hybrid mode downloads all files with more than one at he time and then ffmpeg does it job faster since the local copy is much faster to access than the online version.

Thanks Mate, waiting for the update take your time and thanks again for the work !

**Comment by Serpentstar** [comment] 2022-10-19 16:53
What I am seeing is "not available in my country" for everything.  I am still using the base v3.8.9 build because the other wouldn't work.  So that could be playing with it as well.  None of the previous posts mentioned it.

**Comment by MaybeAA** [comment] 2022-10-19 17:26
@hama3254 do you think it gonna be available today ?

**Comment by hama3254** [comment] 2022-10-19 17:40
@MaybeAA i would say it's unlikly to be done before saturday

**Comment by MaybeAA** [comment] 2022-10-19 17:48
> @MaybeAA i would say it's unlikly to be done before saturday

Oh i see, btw another question do you think making the same tool but for Netflix and Disney+ for exemple ?

**Comment by mikecj92** [comment] 2022-10-19 20:19
I see it started to happen to you like 6 hours ago, this happened just now for me (Mexico User) so I think it started like Phases on all LA

**Comment by Borufanss** [comment] 2022-10-19 22:55
prueba ver si esto te ayuda tal vez crunchyroll haya cambiado de api 

https://github.com/crunchy-labs/crunchyroll-go

**Comment by Borufanss** [comment] 2022-10-19 23:03
Hay alguna posibilidad de que hagas el programa de crunchyroll downloader pero para Netflix?

**Comment by CavemanTechandGamming** [comment] 2022-10-20 01:16
@hama3254 wanted to say thank you for your hard work and making this thing actually work. Can't wait to see it working again after today's update on Crunchyroll side breaking it. Not trying to rush you just saying thank you and I'll be missing it while it's gone.

**Comment by mikecj92** [comment] 2022-10-20 01:29
Hey I had a free time today and I tried to clone the project and compile it, but I got a lot of problems with the reference,  Metroframework and request handler, any of the nuget  library matches your own :(

**Comment by pratyushpati11** [comment] 2022-10-20 08:00
Hey .Any updates on the CR URL issue?

**Comment by MaybeAA** [comment] 2022-10-20 08:08
@hama3254 Hey, i saw on another github crunchyroll post that apparently they just updated the API idk if it's that but hope it can help u xd

**Comment by hama3254** [comment] 2022-10-20 08:21
@pratyushpati11 still the same as yesterday, it's not gonna be done before Saturday.
Crunchyroll did choose the worst time for that with the middle of the week.
I have a full time job besides this project so i don't have much time until Friday, in addition i have already planned something for Friday.

**Comment by hama3254** [comment] 2022-10-20 08:24
@MaybeAA i did not see any changes besides the url, i just don't get access the same way anymore.
I have to see what I am missing inside the request to get 403 as response within the download but my Firefox can open the same url with no trouble.

**Comment by MaybeAA** [comment] 2022-10-20 08:25
@hama3254 i see well good luck !

**Comment by Serpentstar** [comment] 2022-10-20 08:38
@hama3254 And I think I can speak for everyone using your program, we all greatly appreciate the excellent work you are doing.  All most people do is complain when things don't work, and I just want to say thank you for your efforts.

**Comment by ByteDream** [comment] 2022-10-20 11:02
@hama3254 Crunchyroll added a cloudflare security / bot check (or they may had it every since on their main domain). It does a pretty good job of detecting requests that are not sent from a browser.

**Comment by Borufanss** [comment] 2022-10-20 15:28
para cuando volvería a funcionar el programa? Para antes del sábado?

**Comment by hama3254** [comment] 2022-10-20 16:34
A very early version is available, please be patient while using i have to load everything with the webbrowser and that takes a view seconds.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev
On a related note does CR load slower than usual or do they just don't like the amount of access from me?

**Comment by Mayansito** [comment] 2022-10-20 16:36
![image](https://user-images.githubusercontent.com/98242308/197007234-a510f482-c527-4fe4-a53b-68bbf6c546d0.png)

**Comment by ZioBomba** [comment] 2022-10-20 16:37
> ![image](https://user-images.githubusercontent.com/98242308/197007234-a510f482-c527-4fe4-a53b-68bbf6c546d0.png)

Same problem

**Comment by Mayansito** [comment] 2022-10-20 16:58
![image](https://user-images.githubusercontent.com/98242308/197011893-a90eb660-105f-419b-901a-9f5cdce6f983.png)

Only downloading video.

**Comment by MaybeAA** [comment] 2022-10-20 17:02
@hama3254 yo someone updated his downloader for crunchyroll and it work fine maybe u can check his edits 
![image](https://user-images.githubusercontent.com/89535928/197012650-12dc0482-1550-448f-ad78-8fb9e9ada26c.png)

**Comment by hama3254** [comment] 2022-10-20 17:02
@Mayansito please check the output file, i dont think i ever fixed that part so `none`
![grafik](https://user-images.githubusercontent.com/52826614/197012685-b039b98d-6eba-4852-8d22-25a2353476c7.png)

**Comment by Borufanss** [comment] 2022-10-20 17:17
> 

Funciona un poco pero no permite descargar doblajes

**Comment by Mayansito** [comment] 2022-10-20 17:21
![image](https://user-images.githubusercontent.com/98242308/197016307-8b647207-cc33-4abf-be8c-700e098e4ce7.png)
Working but is strange xd

**Comment by Borufanss** [comment] 2022-10-20 17:23
Pude descargar una vez pero ahora no me deja descargar nada

![Screenshot (14)](https://user-images.githubusercontent.com/116229346/197016768-6b98ce4b-308b-40f5-8f8e-ea86b399366b.png)

**Comment by Borufanss** [comment] 2022-10-20 17:30
Gracias!!! Me funciono ahora por iniciarlo en modo administrador

**Comment by Serpentstar** [comment] 2022-10-20 17:32
This is the same thing I was getting before, which is why I didn't go past 3.8.9.  It stops right here.
![image](https://user-images.githubusercontent.com/751507/197018068-a07a8c21-ed28-4de8-ba97-dd336995bd21.png)

[browser.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/9832561/browser.log)

**Comment by Mayansito** [comment] 2022-10-20 17:42
> This is the same thing I was getting before, which is why I didn't go past 3.8.9. It stops right here. ![image](https://user-images.githubusercontent.com/751507/197018068-a07a8c21-ed28-4de8-ba97-dd336995bd21.png)
> 
> [browser.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/9832561/browser.log)

Execute CR Downloader on Admin mode, go inside the anime chapter (on your web browser), let the page load and then copy the link and use it on CR Downloader. The same was happenign to me before and that worked for me.

**Comment by Serpentstar** [comment] 2022-10-20 18:04
That didn't help.

![image](https://user-images.githubusercontent.com/751507/197023446-06dd662b-f5a0-4a40-b534-0d29851f681a.png)
![image](https://user-images.githubusercontent.com/751507/197023465-286f3223-3381-4493-9940-309d7d9069a7.png)

I just can't get past the status of Processing URL 1
[browser.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/9832753/browser.log)

I am trying to figure out what is throwing the _because it violates the following Content Security Policy directive:_ portion of the error.

**Comment by pruebark9** [comment] 2022-10-20 18:08
It works! It just takes much longer before starting a download but it is more than enough. Thanks for your time and work.

**Comment by Borufanss** [comment] 2022-10-20 18:53
> ¡Funciona! Solo toma mucho más tiempo antes de comenzar una descarga, pero es más que suficiente. Gracias por su tiempo y trabajo.
> 
> EDITAR:
> 
> Descargué 2 caps sin problema y lo cerré. Ahora lo he abierto de nuevo y no hay forma de iniciar sesión, siempre dice "algo salió mal" y no lo acepta D:

debes ejecutarlo en modo administrador para que te funcione

**Comment by pruebark9** [comment] 2022-10-20 18:54
> > ¡Funciona! Solo toma mucho más tiempo antes de comenzar una descarga, pero es más que suficiente. Gracias por su tiempo y trabajo.
> > EDITAR:
> > Descargué 2 caps sin problema y lo cerré. Ahora lo he abierto de nuevo y no hay forma de iniciar sesión, siempre dice "algo salió mal" y no lo acepta D:
> 
> debes ejecutarlo en modo administrador para que te funcione

Sí, eso hago. Funcionó a la primera pero a la segunda ya no logea.

**Comment by petenun** [comment] 2022-10-20 19:38
Great progress, @hama3254! I very much appreciate the time you've spent on this, even with work and other plans. I wanted to describe my experience below, not to rush things, but to provide you with additional information that might aid you.  

My experience with v3.9-Indev. Scenario: Downloading three full seasons of RWBY (https://www.crunchyroll.com/series/GRNQJM89R/rwby):

- The application launches without error. 

- As described, when adding video, it's much slower in resolving URLs, giving a 10 second countdown before the episode selection, but after the wait all videos queue up. Repeated seasons behave the same way, but all episodes appear to queue-up as expected.  

- When finally processing the queue, each separate video in the queue gives a 10 second countdown before download starts. Again, slow but functional. 

- However, with three seasons of episodes queued, it only made it through about 14 episodes in queue before the program became unresponsive.

Great progress so far! At least it's partially functional. I've attached the execution log in case that helps.

[Execution Log.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/9833393/Execution.Log.txt)

**Comment by 619beave** [comment] 2022-10-20 22:57
Ran the program in admin mode, still get 
<img width="1920" alt="Screenshot 2022-10-20 15 57 07" src="https://user-images.githubusercontent.com/41927382/197074516-69234e9c-63cd-4255-a930-3deb1927ba19.png">

Thread Name: Main
Web server started at: 127.0.0.1:8080
Basic bm9haWhkZXZtXzZpeWcwYThsMHE6
FrameLoadEnd10/20/2022 3:54:20 PM
get html
10/20/2022 3:54:20 PM.440
https://www.crunchyroll.com/
Just Browsing, exiting...
Start loading: 10/20/2022 3:54:27 PM
FrameLoadEnd10/20/2022 3:54:28 PM
get html
10/20/2022 3:54:28 PM.707
https://www.crunchyroll.com/watch/G8WUNXJJ8/getting-carried-away-100
0
10/20/2022 3:54:38 PM Thread Name: Main

**Comment by Borufanss** [comment] 2022-10-20 23:05
> Ejecutó el programa en modo de administración, aún obtuve <img alt="Screenshot 2022-10-20 15 57 07" width="1920" src="https://user-images.githubusercontent.com/41927382/197074516-69234e9c-63cd-4255-a930-3deb1927ba19.png">
> 
> Nombre del hilo: Servidor web principal iniciado en: 127.0.0.1:8080 Basic bm9haWhkZXZtXzZpeWcwYThsMHE6 FrameLoadEnd10/20/2022 3:54:20 PM obtener HTML 10/20/2022 3:54:20 PM.440 https://www.crunchyroll.com/ Simplemente navegando, saliendo ... Comience a cargar: 10/20/2022 3:54:27 PM FrameLoadEnd10/20/2022 3:54:28 PM obtener html 10/20/2022 3:54:28 PM.707 https://www.crunchyroll.com/watch/G8WUNXJJ8/getting-carried-away-100 0 10/20/2022 3:54:38 PM Nombre del hilo: Principal

Alv me gusto tu fondo de pantalla me lo podrias compartir para poder usarlo?

**Comment by Borufanss** [comment] 2022-10-20 23:32
Alguien sabe cual es la mejor configuración de crunchyroll downloader para poder descargar muy rápido? porque hasta ahora no consigo que se descarguen muy rápido

**Comment by Serpentstar** [comment] 2022-10-20 23:34
@Borufanss At least you can get it to work.  I get stuck at the Processing URL 1 point and it never progresses further.  At least it's nice to know I am not the only one being blocked by that.

**Comment by Borufanss** [comment] 2022-10-20 23:47
> @Borufanss Al menos puedes hacer que funcione. Me quedo atascado en el punto Processing URL 1 y nunca progresa más. Al menos es bueno saber que no soy el único bloqueado por eso.

Porque algo estás haciendo mal o hayas configurado mal

**Comment by Serpentstar** [comment] 2022-10-21 00:27
@Borufanss Feel free to enlighten me on what I am doing wrong.  I have been unable to use any of the versions after v3.8.9 as something in the code changed then.  

I have gone through and ripped everything out of the registry, deleted all the old files and extracted the new one to its own folder and I still end up hard stopping at the URL1

**Comment by hama3254** [comment] 2022-10-21 08:09
@Serpentstar please open the build-in Webbrowser and see what it's doing after it goes to `processing 1`.
It should load the streams json (data for the video) which then has to trigger the objects json (data for the name) and it should not be dependent on any setting.

**Comment by ms-ku** [comment] 2022-10-21 08:35
Hello hama3254

Is there a new C++ required? 
With v3.9_Indev (out of the box) i cannot change any Settings. I got this error message 

![grafik](https://user-images.githubusercontent.com/67540232/197150612-99a20614-8ffd-47b7-aa6d-8ed090cfba36.png)

Till Snapshot version there is no Problem with it.
Otherwise the download works sometimes but usually i have the same problem as Serpentstar.
Thanks and greetings

**Comment by MaybeAA** [comment] 2022-10-21 10:32
Can someone explain me how we rlogin on our crunchyroll account since the web page is broken ? please

**Comment by hama3254** [comment] 2022-10-21 11:25
@ms-ku that is probably some error i made inside the settings save button, i see what that is about.

**Comment by Mayansito** [comment] 2022-10-21 18:16
> Hello in my case the Problem is reproducible Here the download is working without any Problems (like old times)
> 
> https://www.crunchyroll.com/de/series/G6MEK1ZGR/kakuriyo--bed--breakfast-for-spirits-
> 
> and here not - Problem as described above
> 
> https://www.crunchyroll.com/de/series/GYP84XNVY/kaze-no-stigma
> 
> By the way (in my case) - the login data will not be saved. After restarting the Dowmloader i have to Login again.
> 
> Sorry for my bad english, google is not the best translator ;-)
> 
> Greetings msku

For data being saved, you have to open CR Downl with Administrator mode and log in.

**Comment by hama3254** [comment] 2022-10-21 19:03
[Crunchyroll-Downloader-v3.9_Indev_U2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev) is now available!
For every issue related to this version i would suggest using issue #553

**Comment by petenun** [comment] 2022-10-21 19:08
Other observations:

- When using v3.9-Indev, using built-in browser to browse shows works fine, however when diving in to a specific episode (as if to play) produces "Oops! Something went wrong. Try again." response from Crunchyroll. Performing the same operation in Chrome (Version 106.0.5249.119) allows the episode to load (and play if desired). Could CR be explicitly blocking the v3.9-Indev reported browser version?

- Latest Windows and .NET updates (October 2022) do not make any difference in behavior.

- Rebooting workstation does not make any difference in behavior.

- After my initial partial-success, I have not been able to reproduce a successful scenario. All roads still lead to the 10 second countdown, stalling when it reaches 1.

- Running as Administrator does not appear to accomplish anything. Behavior is the same and CR Log-In token is not saved, requiring new log-in with each successive program launch.

**Comment by Borufanss** [comment] 2022-10-21 20:10
> [¡Crunchyroll-Downloader-v3.9_Indev_U2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev) ya está disponible! Para cada problema relacionado con esta versión, sugeriría usar el número [# 553](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/553)

Funciona perfecto y descarga muy rapido!!! Te agradezco mucho por tu esfuerzo de hacer este programa funcionara de nuevo pero hay un problema no le podrias quitar la cuenta regresiva al querer descargar algo?

**Comment by Borufanss** [comment] 2022-10-22 11:42
> @Borufanss Al menos puedes hacer que funcione. Me quedo atascado en el punto Processing URL 1 y nunca progresa más. Al menos es bueno saber que no soy el único bloqueado por eso.

a mi me paso lo mismo cuando queda en Processing URL 1 prueba en darle download y empieza a descargar

**Comment by hama3254** [comment] 2022-10-22 12:09
[Crunchyroll-Downloader-v3.9_Indev_U3](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev) is now available!

**Closed** 2022-10-23 19:36 UTC
