### ISSUE TITLE
download crashes

### ISSUE THREAD

**Issue by ncplus0** [hama3254/Crunchyroll-Downloader-v3.0#115] opened 2020-12-18 23:46 UTC
when i add a episode he detects the resolution and language also subtitles but then it crashes

exemple: 
https://www.crunchyroll.com/en-gb/cherry-magic-thirty-years-of-virginity-can-make-you-a-wizard/episode-3-untitled-800211

i manage to do the 1 and 2 episode but the 3 and 4 it does not download, and if a do the network scan in only downloads 50% the episode

I'm using the v3.6.8, also tried the v3.6.7, and is still the same, but when i tested with version v3.6.5, it works, so it something wrong with the code

**Comment by hama3254** [comment] 2020-12-19 12:25
You need to tell me the settings you have used, it's impossible to find the error you might have otherwise : 
![grafik](https://user-images.githubusercontent.com/52826614/102689309-60b5f180-41fd-11eb-916f-0f11657d92a2.png)

**Comment by hama3254** [comment] 2020-12-19 12:48
> and if a do the network scan in only downloads 50% the episode

it seems to me that it just downloads the middle part between the first and the second ad.

**Comment by ncplus0** [comment] 2020-12-20 14:58
i send you the definitions options
i've tried again with the new version and still does not download
the 6th picture is the bug

![Untitled1](https://user-images.githubusercontent.com/72767232/102716346-3fbfd000-42d3-11eb-9d4d-87e5570eab98.jpg)
![Untitled2](https://user-images.githubusercontent.com/72767232/102716347-40f0fd00-42d3-11eb-9034-03b58f599b79.jpg)
![Untitled3](https://user-images.githubusercontent.com/72767232/102716348-42222a00-42d3-11eb-9b5d-7a246371f963.jpg)
![Untitled4](https://user-images.githubusercontent.com/72767232/102716349-42bac080-42d3-11eb-83bd-89f011962d4f.jpg)
![Untitled5](https://user-images.githubusercontent.com/72767232/102716350-43535700-42d3-11eb-9a64-71a167cf0789.jpg)
![Untitled6](https://user-images.githubusercontent.com/72767232/102716413-ae9d2900-42d3-11eb-8e98-ccfc71555845.jpg)

**Comment by hama3254** [comment] 2020-12-20 19:35
Thanks for the data, on the first look i see that some of your settings might not be the best choice.
You have enabled soft subtitle and"Merge soft-subs with video file" while using Hard subtitle, that works but defeats the purpose of soft subtitle which can be turned on and off. 

Now to your problem, i still can not reproduce the problem even with your settings and the network address as path.
I'm have also no idea why v3.6.5 woks but later version that have no change to the parts you are using with that settings does not. 
Since you have the logfile enabled you could send it to me here, it should contain the exact error.
You find the .log file with the same name as the episode should have in the folder which you have selected in the downloader.

**Comment by ncplus0** [comment] 2020-12-21 00:18
it started working again, i've, change the folder that was on network folder and the save was also on network folder and change to my pc and it worked, also eaven with the log option activated it did not create a log, so the problem was execute and save on network server

**Comment by hama3254** [comment] 2020-12-21 11:05
>  so the problem was execute and save on network server

as i said, i tried that 

> i still can not reproduce the problem even with your settings and the network address as path.

so the issue is most likely your network folder itself. 
but as long it works now i can close this.

**Closed by hama3254** 2020-12-21 11:05 UTC
