### ISSUE TITLE
Unlock US cookies not return any result

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#25] opened 2020-06-05 12:27 UTC
When i tried to unlock the US Cookies, the program not return with any result either unlock successfull or not.

And the result is program still not able the US content, hope can fix asap.

**Comment by hama3254** [comment] 2020-06-05 18:13
it was down for less than 10 minutes due to changes on the webserver, it should work again but only in v3.2.5

**Comment by x3inspire** [comment] 2020-06-06 01:01
I'm using v3.2.5 now still same, cannot unlock US content. Can you help verify?

**Comment by hama3254** [comment] 2020-06-07 11:45
> 
> 
> I'm using v3.2.5 now still same, cannot unlock US content. Can you help verify?
i can verify that it is working with the limitaions i have added to the YT comment.

>[Info]
>Update US Unlock:
>with v3.2.5 i have reanabled the us unlock, keep in mind it does not work while logged in!
>https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/

**Comment by x3inspire** [comment] 2020-06-07 15:12
Ah, so it not working if we loged in our account. So cannot download latest episode :(

Is there any changed from Crunchyroll? Because old version before this working fine.

**Comment by hama3254** [comment] 2020-06-07 17:10
> 
> Is there any changed from Crunchyroll? Because old version before this working fine.

CR changed the behavior so i can no longer overwrite the country.
i'm working on a fix for that.
the original firefox addon has the same problem :
https://cr-unblocker.us.to/

**Comment by x3inspire** [comment] 2020-06-08 01:08
I noticed if we are using VPN, CR will emailed us the notification and we need to take action to allow the IP can be access or not. Does it effect to US Unlocker as well?

**Comment by hama3254** [comment] 2020-06-08 09:50
> I noticed if we are using VPN, CR will emailed us the notification and we need to take action to allow the IP can be access or not. Does it effect to US Unlocker as well?

I need to look at this later after work.
I can confirm for now that they send and email, but I don't need to do anything it is just a notification.
I made yesterday a Demo with US unlock and login for reddit.
For now it looks like I got an email before the video because of a VPN but not for the video itself.
https://www.reddit.com/r/hama3254/comments/gyaxju/us_unlock_progress/

**Comment by x3inspire** [comment] 2020-06-08 14:01
Waiting for new version!

**Comment by x3inspire** [comment] 2020-06-10 23:54
Fantastic, now can unlock US cookies.

But i noticed the apps not canceled the download task properly, same goes for overwrite function.

I got stuck one video at 30%, when i do cancel it wont canceled, and then when i tried to redownload again it only asked for overwrite but not download anything. Had to close the whole program, delete the unfinished file and start download again.

**Comment by x3inspire** [comment] 2020-06-11 02:27
Hi, seem like unlock US cookies stuck at:

`javascript:document.cookie ="session_id=6f99e77d0deb12e6ac20bafe52f0b9f5; expires=Thu, 05 Jan 2021 00:00:00 UTC; path=/;";`

**Comment by hama3254** [comment] 2020-06-11 07:35
> Hi, seem like unlock US cookies stuck at:
> 
> `javascript:document.cookie ="session_id=[don't share cookies!]; expires=Thu, 05 Jan 2021 00:00:00 UTC; path=/;";`

First of all remove the value of the cookie before posting, it can give others acces to your account.

To the problem, there a two ways you can stuck there.
1. You closed the login window
2. You did not use the login window 
This should not be a big problem because the only what should happen thing after that is reloading Crunchyroll.
And well I moved that into the submit button of the login window.

**Comment by x3inspire** [comment] 2020-06-19 11:01
Hi,

1. You closed the login window
Nope, after submit captcha i just waiting for the next step for put my user and password.

2. You did not use the login window
I did

**Comment by hama3254** [comment] 2020-06-26 17:44
> 
> 
> Hi, seem like unlock US cookies stuck at:
> 
> `javascript:document.cookie ="session_id=[don't share cookies!]; expires=Thu, 05 Jan 2021 00:00:00 UTC; path=/;";`

is fixed in v3.3

**Closed by hama3254** 2020-06-26 17:44 UTC

**Comment by x3inspire** [comment] 2020-08-17 13:12
Hi, seem like Unlock US not working anymore. Can you help check please, and possible to change the captcha to easy mode please?

**Comment by MobCode100** [comment] 2020-08-20 03:47
Same goes for me
