### ISSUE TITLE
The download process seems to have crashed

### ISSUE THREAD

**Issue by josesoto12** [hama3254/Crunchyroll-Downloader-v3.0#54] opened 2020-09-17 16:10 UTC
For the first time I have used the funimation function, but it does not download the file (or so it seems).
Also just download a vtt file.
![Error q](https://user-images.githubusercontent.com/71455273/93497762-6cc8a500-f8d6-11ea-9a9b-ff56f2a87557.JPG)
![error w](https://user-images.githubusercontent.com/71455273/93497775-7225ef80-f8d6-11ea-9a14-13e579fdb7f5.JPG)

**Comment by hama3254** [comment] 2020-09-17 17:22
please enable the log file and provide me the result. 
you can activate it in the settings and the log get saved in the download directory with the same name as the video file
<details>
<summary>log setting</summary>

![grafik](https://user-images.githubusercontent.com/52826614/84301783-a6aa4280-ab54-11ea-8fae-09de14fda064.png)
</details>

<details>
<summary>log save name example</summary>

![grafik](https://user-images.githubusercontent.com/52826614/92991957-5d68e680-f4e7-11ea-8a9c-5bf63510b9b6.png)
</details>

**Comment by josesoto12** [comment] 2020-09-18 19:41
I did what you told me, but still can't download the video file.
I am attaching the screenshots corresponding to the files that are downloaded and the process carried out in Crunchyroll Downloader, as well as attaching the content of the file that is downloaded.
![Error q](https://user-images.githubusercontent.com/71455273/93638445-f18dee80-f9bc-11ea-81ab-4be05c8de61b.JPG)
![error w](https://user-images.githubusercontent.com/71455273/93638474-fbafed00-f9bc-11ea-9b62-a3211d099ce0.JPG)
[Dragon Ball Season 1 Episode 1.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5247803/Dragon.Ball.Season.1.Episode.1.log)

**Comment by hama3254** [comment] 2020-09-18 20:18
thanks for the log, i clearly see the problem but i don't understand how this might happen. 
the error is simply a access problem, i don't get this error with my US VPN (i'm from Europe) so i can only add a check for this an if this happens i can use the next stream of that resolution 
`[https @ 06f9c500] HTTP error 403 Forbidden`

**Comment by josesoto12** [comment] 2020-09-18 20:25
You're right. I had suspicions that it was a VPN problem.  But could you tell me which VPN you use? Maybe that way it will be able to download.

**Comment by hama3254** [comment] 2020-09-18 20:38
i have setup my own OpenVPN server on a rented virtual server which also serves as web server for the crunchyroll us unlock

**Comment by hama3254** [comment] 2020-09-18 20:57
if you want to try i made a version that should in theory check every available stream before downloading, to be precise it checks the key file which was the issue in your log 
`18/09/2020 02:32:03[hls @ 06563b80] Opening 'https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1328034/English/1328034_English_a6365004-7051-e711-8175-020165574d09_Layer10_0.key' for reading
18/09/2020 02:32:04[https @ 06f9c500] HTTP error 403 Forbidden`

https://mega.nz/file/sAsD0QSY#UBPzeJ37Y9CRE2R-7RYSOfRVNscFJD5q5xtGvykKp4k

**Comment by hama3254** [comment] 2020-09-30 17:07
without hearing any other complaint i guess the issue is no longer here so i close this issue.
if there is still some issue you can create a new issue.

**Closed by hama3254** 2020-09-30 17:07 UTC
