### ISSUE TITLE
Captcha-ception?

### ISSUE THREAD

**Issue by sinnx3** [hama3254/Crunchyroll-Downloader-v3.0#48] opened 2020-09-05 18:46 UTC
Why is it everytime I have to set a cookie I have to go through 20+ captcha's.

And when you do solve them correctly, it redirects to more captcha's then FINALLY it lets you set your cookie.

Captcha system is flawed HORRIBLY.

**Comment by hama3254** [comment] 2020-09-06 10:19
> through 20+ captcha's.

i have known that it does not work as intended but the data don't show it that bad.
i have already tryed other methods but [like here](https://criater-stiftung.org/) but it is not secure so i did not change the us unlock on the api site. 
![grafik](https://user-images.githubusercontent.com/52826614/92323613-64e94500-f03a-11ea-93da-1272b09950be.png)

**Comment by hama3254** [comment] 2020-09-06 17:38
You can try to use this version : https://api.criater-stiftung.org/test-new.php
just open the us unlock as usual and replace the url and press the 'Enter' Key
![grafik](https://user-images.githubusercontent.com/52826614/92331621-6fc2ca80-f078-11ea-9095-4c2b4494d9ad.png)

**Comment by hama3254** [comment] 2020-09-17 17:30
it seems to work from what i see on the server so i close this and add the new methode in the future.

**Closed by hama3254** 2020-09-17 17:30 UTC
