### ISSUE TITLE
Different issues I am facing and improvement

### ISSUE THREAD

**Issue by TheWizard-maker** [hama3254/Crunchyroll-Downloader-v3.0#771] opened 2023-06-24 19:55 UTC
Hi,
 
He are some issues I am facing with the downloader.

- When I want to download several episodes in a row. At one moment the downloader finish an episode and doesn't start the next one. That can happen after 2,5 or 8 episodes.
- Sometimes, the episode downloaded is 10-15 secondes shorter than it should be. It is because 10-15s are cut in the middle of the episode and they are missing. So when I want to merge several different language, i have a problem of synchronisation
- 
Are they common problem or a problem of configuration I have created by using some wrong parameter

**Comment by hama3254** [comment] 2023-06-24 22:16
> * When I want to download several episodes in a row. At one moment the downloader finish an episode and doesn't start the next one. That can happen after 2,5 or 8 episodes.

are they marked as finished by the downloader?


> * Sometimes, the episode downloaded is 10-15 secondes shorter than it should be. It is because 10-15s are cut in the middle of the episode and they are missing. So when I want to merge several different language, i have a problem of synchronisation

This could be two problems in one. 
Merging will result in some issues like mentioned in #701 since there is never any garentuie that the different videos are in sync to begin with.

For actuall loss of parts from the video you can use the `Hybrid Mode` and the `Error handling`.
The `Hybrid Mode` is the downloader caching the stream data before processing it with a external tool to give me more controll over the behavior like retrying failed downloads and higher timeouts. 
The `Error handling` is disabled by defaul but you can set it to 1 which makes the downloader stop the download letting you know it's missing something.

**Comment by TheWizard-maker** [comment] 2023-06-25 01:34
> are they marked as finished by the downloader?
Yep, the situation is like frozen, nothing change anymore

I tried with the configuration you suggest and it is much better but it still stop automatically. I tried 2 times : first time after episode 11 and second time after episode 16 
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/f44ebb23-2d43-4cfb-a375-9875b6658b85)

It looks like i don't have anymore the issue of 10-15 sec missing


- Could you please explain me how to use the queue. Is it possible to use it if I want fist to download an anime with japanese audio and a second time with an other audio language

**Comment by TheWizard-maker** [comment] 2023-06-25 01:46
and i tried with hybrid mode - keep cache and the first episode doesn't start

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/c4ce4846-e535-4915-86d6-fba4b8644a31)

**Comment by hama3254** [comment] 2023-06-25 08:21
for the episode that does not start i would need the [Log file](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile) to check the issue.

**Comment by TheWizard-maker** [comment] 2023-06-25 13:36
Should I copy and paste it here or do you prefer an other way to provide you the log file ?

**Comment by TheWizard-maker** [comment] 2023-06-25 14:33
[Nouveau Document texte (2).txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/11859967/Nouveau.Document.texte.2.txt)

**Comment by hama3254** [comment] 2023-06-25 15:00
> [Nouveau Document texte (2).txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/11859967/Nouveau.Document.texte.2.txt)

i assume that log is for a download that finished but the downloader does not continue with the next download ?
This log is fine, i can not see any issues there. This is not surprising since :

>>are they marked as finished by the downloader?

>Yep, the situation is like frozen, nothing change anymore


just to be on the same page, this are total downloads (running + finished) ?

>That can happen after 2,5 or 8 episodes.

i wanted the log for the episode that does not start at all.

> and i tried with hybrid mode - keep cache and the first episode doesn't start
> 
> ![image](https://user-images.githubusercontent.com/110522591/248521990-c4ce4846-e535-4915-86d6-fba4b8644a31.png)


for the freezing problem i would need the version of the downloader (can be found in `Settings` (gear icon) -> `About` tab and then the number behind `You have: `

i would also nice to know the used windows version and the PC hardware you have, the downloader is not that well written or optimized

**Comment by TheWizard-maker** [comment] 2023-06-25 22:42
> _just to be on the same page, this are total downloads (running + finished) ?_
If i explain with an exemple, the download of the episode 16 is finished and the download of the episode 17 never start. This looks like from an external point of view that occurs a little bit ramdomly
For example if i try 1 time, that will happen at episode 16 (16 finished / 17 doesn't start
if i try again with the same season of the same anime i have 11 finished / 12 doesn't start
if i start download from episode 15, i can download until the end of the season 1 (episode 24)
For this I cannot provide any log file, as the download doesn't start, the episode doesn't appear on the main screen so i cannot do right clic on it.

_`i wanted the log for the episode that does not start at all.`_
[log.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/11861133/log.txt)

f_`or the freezing problem i would need the version of the downloader (can be found in Settings (gear icon) -> About tab and then the number behind You have:`_ 
I use the latest one 3.15.5

_i would also nice to know the used windows version and the PC hardware you have, the downloader is not that well written or optimized_
window 10 intel core i5 8300H 230Ghz 16Go Ram RTX 2060
I know with my new computer (R9 7900X 32Go Ram RTX 4070Ti I have still the problem when the downloader finish an episode and doesnt start the next one. For the other problem, i cannot say because i didn't try. I dont download often with my big PC

**Comment by TheWizard-maker** [comment] 2023-06-28 02:08
Do you think the problem is linked to my computer or does it take time to analyse why that happen ?

**Comment by hama3254** [comment] 2023-06-29 08:32
The hardware side does look more than enough.
I have trouble re-creating this issue, I suspect something does not work right at your end.

If that problem was with just a view episodes (<12 episodes) than there would be more reports like yours.
The two last reports with issues on the download counts where #745 and #759.
Those two claimed 41 as braking point.

**Comment by TheWizard-maker** [comment] 2023-06-29 15:03
Thanks for your answer. I don't know if that matter but my protection system is avast and avast block every download with your downloader. They don't even start downloading audio or subs. 
So i use to desactivate it when I want to use you downloader but I don't know if it is avast or an other app which creates that issue. Do you have an idea ?

**Comment by hama3254** [comment] 2023-07-02 16:14
i don't use any 3rd party security software and i don't know how your might breake the downloader.
this limits the help i can give you.
you could try another computer or try to isolate the downloader from the system with a virtual computer, free software like the `vmware player` allows you to make a computer in the computer with a clean Windows 10 version.

**Comment by TheWizard-maker** [comment] 2023-07-05 09:31
Thank you for your answer. I think everything is working fine. 
I have noticed something when i have downloaded the season 6 of my hero academia
I don't know if we can call it an issue : I have for some episode the english sur is webvtt and not SubstationAlpha. 2 or 3 episodes are concerned. Is it how they are on crunchyroll or a bug ?

**Comment by hama3254** [comment] 2023-07-05 14:29
you might want to check if you have captions enabled in the settings, they are usually `vtt` files.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/3d860aa7-427c-4589-b517-674866f08d4e)

**Comment by TheWizard-maker** [comment] 2023-07-05 18:01
Thank you for your answer. I think everything is working fine. 
I have noticed something when i have downloaded the season 6 of my hero academia
I don't know if we can call it an issue : I have for some episode the english sur is webvtt and not SubstationAlpha. 2 or 3 episodes are concerned. Is it how they are on crunchyroll or a bug ?

**Comment by TheWizard-maker** [comment] 2023-07-05 18:05
Here is how i have configured the downloader. I don't know if i do something wrong
I like to download all audio et sub available and then merged all together in one mkv file
so i download all season for each language and then merge manually
![Crunchyroll Downloader - Settings About](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/4683fa5e-336d-4d6b-90cf-97ac81e7aa68)
![Crunchyroll Downloader - Settings Cunchyroll](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/8b7a2c25-d735-4e52-bfe6-c5d307c10f8a)
![Crunchyroll Downloader - Settings Funimation](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/c2a0249a-e63f-4215-b33a-1b37cf9b1121)
![Crunchyroll Downloader - Settings Main](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/517792cb-e0d1-4682-a03a-6cfd003a2a12)
![Crunchyroll Downloader - Settings Naming](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/5fdea561-f41b-4dc5-872e-37618256641c)
![Crunchyroll Downloader - Settings Output](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/3bf3e8ed-39d0-40bd-86d0-f6a5e1e00c6b)

**Comment by hama3254** [comment] 2023-07-06 09:42
The settings look fine, you should not get webvtt subtitles with them.

One thing to note please try to use the latest version.

To find the cause of the webvtt subtitles it would be nice to know what the subtitles are exactly.
It is possible to have the downloader use the wrong extension (`vtt` not `ass`) for the right file.
It is also that the exact opposite happens (`ass` as extension but it gets a `vtt` file) or is it really a file with `vtt` as extension with the content as `WEBVTT`?

**Comment by TheWizard-maker** [comment] 2023-07-07 02:45
so i tried to download 3 times the english sub of the 1st episode of the 6th season of my hero academia
everytime the extension is ass but the content is the one of a webvtt file

**Comment by TheWizard-maker** [comment] 2023-07-07 03:22
This is an ass file but here is how it is if i open it 
![sub](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/d89b17e4-9b1f-4fc5-a156-84a05e2effa8)

**Comment by TheWizard-maker** [comment] 2023-07-07 09:19
from an issue to an other 
I have this when i downloaded the 2nde season of demon slayer
finished for every download but the folder temporary is still there.

![crunchy](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/40b7e243-3b1a-41e0-83de-fc5fafe749a9)

**Comment by TheWizard-maker** [comment] 2023-07-08 04:33
Since I am using the latest version (3.15.5.3) the download stopped for some episodes with the message "missing segment..."
That happen for exemple with the episode 133 of my hero academia (english dub). I tried 5 times to download the 6th season and it always stoppes at epsiode 133 close to the end (at the same segment)

**Comment by hama3254** [comment] 2023-07-14 18:20
> Ok I have downloaded the latest version and selected "remove CC style" and its works now for that episode. I have a "real" ass and not a vtt anymore. What the remove CC style doing ? (want to be sure it is what i need)

with `ass` you don't need it. It only affects `vtt` files for the CC option. (see #769)

>an other thing i have selected remove CC style but if i open the settings, the "remove cc style" is not selected anymore ? is it normal ? does it mean I have to open the setting and select it each time i open the downloader ?

it can disable itself if the setting would not apply anyway. 

>finished for every download but the folder temporary is still there.

the screenshot and the wording `the folder` suggest it's just one? 
usually all downloads have one so if you or your antivirus access one of the folders the deletion might fail, the downloader try's again if you close it.
in the worst case you can delete them by and later.


> Since I am using the latest version (3.15.5.3) the download stopped for some episodes with the message "missing segment..."
> That happen for exemple with the episode 133 of my hero academia (english dub). I tried 5 times to download the 6th season and it always stoppes at epsiode 133 close to the end (at the same segment)

you set the `Error Handling` to 1 which tirggers at the first missing segment and pauses the download, you should be able to resume it if you want.
The exact details would be in the [FFMPEG-Logfile](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile)

**Closed** 2023-07-22 06:31 UTC
