### ISSUE TITLE
Simultaneous Download Issue (Persist after patch)

### ISSUE THREAD

**Issue by kanohn** [hama3254/Crunchyroll-Downloader-v3.0#144] opened 2021-01-18 17:34 UTC
Hi,

After some days i tested the new version, and the simultaneous download issue still persist:
https://ibb.co/svPys6Q

This happens when some download finish, the program push and start 2 downloads at same time.

**Comment by hama3254** [comment] 2021-01-19 18:09
The downloader can not start two downloads at the same since there is only one webbrowser which is blocked during the background magic.
since i never had this issue i can not see why it might happens, i amused the last time that the running downloads don't report fast enough there stat as "downloading" so i changed it to every items is "downloading" if it is not marked as "finished".
i take a look at the function for the mass download again.

**Comment by hama3254** [comment] 2021-01-19 21:02
try the v3.7.3.1 just get the `Crunchyroll.Downloader.v3.7.3.1.exe` and copy it into the existing folder of the downloader you get it from here
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.3

**Comment by kanohn** [comment] 2021-01-19 21:44
Ok i will try that and update here.

**Comment by hama3254** [comment] 2021-01-26 16:47
after a week without any reported problems i guess that it works now as intended so i close this now.

**Closed by hama3254** 2021-01-26 16:47 UTC
