### ISSUE TITLE
Download Queue Bug

### ISSUE THREAD

**Issue by DoodleCup** [hama3254/Crunchyroll-Downloader-v3.0#212] opened 2021-03-17 16:53 UTC
If i add more than one item to the download queue the tool always downloads the same link and asks me to override. v 3.7.7

**Comment by hama3254** [comment] 2021-03-17 18:47
i can not reproduce the issue, everything is working fine for me.
if you have more details when it happens please let me know.

**Comment by LordSchwenk** [comment] 2021-03-18 22:21
If i add more episodes from one season this bug appears. I download Episode 1 and add 2 and 3. And it downloads episode 2 and delte episode 3 from the list.

**Comment by hama3254** [comment] 2021-03-19 11:55
I am still not able to find the issue.

https://user-images.githubusercontent.com/52826614/111776353-32a28500-88b2-11eb-9c23-d59514701c13.mp4

**Comment by MSI-Toby** [comment] 2021-03-24 04:22
It looks like it only affects Funimation. I got it to give me an error message once, but not a second time. It just ran through the queue and downloaded nothing. It happened both when I used the internal browser as well as the Firefox plugin. Using version 0.5.0 of the plugin if that matters.

**Comment by LordSchwenk** [comment] 2021-03-27 18:33
I give the Episodes a own name. Maybe thats the reason for the bugs. Or the subtitles... dont know. But its still the problem on every anime on crunchyroll. Even with newest version.

**Comment by hama3254** [comment] 2021-03-27 23:28
> I give the Episodes a own name. Maybe thats the reason for the bugs.

just don't do that. i start clearing the name textbox in the next version so that issue can not occur again.

**Comment by LordSchwenk** [comment] 2021-03-28 14:47
Thank you. Now its working. Hopefully the bug get fixed in the future cause i need to use an own naming pattern for my plex server.

**Comment by hama3254** [comment] 2021-03-28 15:09
You have a little bit of selection for the naming pattern in the settings.

![grafik](https://user-images.githubusercontent.com/52826614/112756973-d9d89800-8fe7-11eb-8edb-b52949d6f075.png)

You can also set custom prefixes for Season and episode.

![grafik](https://user-images.githubusercontent.com/52826614/112756958-ccbba900-8fe7-11eb-9c53-49305a0d8a43.png)

**Comment by hama3254** [comment] 2021-04-01 17:57
This seems to be solved so i close it.

**Closed by hama3254** 2021-04-01 17:57 UTC
